;;;; package.lisp --- package definition for rosette-hott-core.

(defpackage #:rosette-hott-core
  (:use #:cl)
  (:export
   ;; Types
   #:hott-type
   #:hott-type-name
   #:hott-type-predicate
   #:hott-type-truncation
   #:make-hott-type
   #:in-type-p
   #:pointed-type
   #:pointed-type-type
   #:pointed-type-basepoint
   #:make-pointed-type
   #:pointed-map
   #:pointed-map-source
   #:pointed-map-target
   #:pointed-map-function
   #:pointed-map-basepoint-path
   #:make-pointed-map

   ;; Paths / identity witnesses
   #:hott-path
   #:hott-path-type
   #:hott-path-from
   #:hott-path-to
   #:hott-path-witness
   #:make-hott-path
   #:refl
   #:path-inverse
   #:path-compose
   #:path-ap
   #:path-induction
   #:path-recursion
   #:based-path-induction
   #:path-loop-p
   #:path-compose-associative-p
   #:path-left-unit-p
   #:path-right-unit-p
   #:path-inverse-left-p
   #:path-inverse-right-p
   #:path-ap-compose-p
   #:loop-space
   #:loop-refl
   #:loop-compose
   #:loop-power
   #:pointed-map-loop
   #:loop-group
   #:loop-group-pointed
   #:loop-group-carrier
   #:loop-group-equality-test
   #:loop-endpoint-equal-p
   #:make-loop-group
   #:fundamental-group
   #:loop-group-identity
   #:loop-group-compose
   #:loop-group-inverse
   #:loop-group-power
   #:loop-group-equal-p
   #:loop-group-law-report

   ;; Dependent families / transport
   #:hott-family
   #:hott-family-base
   #:hott-family-fiber
   #:hott-family-transport-fn
   #:make-hott-family
   #:family-fiber
   #:transport
   #:transport-refl
   #:transport-compose
   #:transport-refl-p
   #:transport-compose-p
   #:dependent-path
   #:dependent-path-family
   #:dependent-path-base-path
   #:dependent-path-from
   #:dependent-path-to
   #:dependent-path-path
   #:make-dependent-path
   #:dependent-path-valid-p
   #:dependent-action-path

   ;; Equivalences
   #:hott-equivalence
   #:hott-equivalence-source
   #:hott-equivalence-target
   #:hott-equivalence-forward
   #:hott-equivalence-backward
   #:hott-equivalence-left-homotopy
   #:hott-equivalence-right-homotopy
   #:hott-homotopy
   #:hott-homotopy-source
   #:hott-homotopy-target
   #:hott-homotopy-left
   #:hott-homotopy-right
   #:hott-homotopy-witness-fn
   #:make-hott-homotopy
   #:point-homotopy-path
   #:homotopic-on-p
   #:hott-fiber-value
   #:hott-fiber-value-point
   #:hott-fiber-value-image-path
   #:make-hott-fiber-value
   #:homotopy-fiber-type
   #:homotopy-square
   #:homotopy-square-top-source
   #:homotopy-square-top-target
   #:homotopy-square-bottom-source
   #:homotopy-square-bottom-target
   #:homotopy-square-top-map
   #:homotopy-square-bottom-map
   #:homotopy-square-left-map
   #:homotopy-square-right-map
   #:homotopy-square-homotopy-fn
   #:make-homotopy-square
   #:homotopy-square-path
   #:homotopy-square-fiber-map
   #:contractible-witness
   #:contractible-witness-type
   #:contractible-witness-center
   #:contractible-witness-contraction-fn
   #:make-contractible-witness
   #:contraction-path
   #:contractible-on-p
   #:fiberwise-equivalence-witness
   #:fiberwise-equivalence-witness-source
   #:fiberwise-equivalence-witness-target
   #:fiberwise-equivalence-witness-forward
   #:fiberwise-equivalence-witness-fiber-witness-fn
   #:make-fiberwise-equivalence-witness
   #:fiberwise-witness-for
   #:equiv-from-fiberwise-witness
   #:make-hott-equivalence
   #:identity-equivalence
   #:inverse-equivalence
   #:compose-equivalences
   #:equiv-forward
   #:equiv-backward
   #:equiv-path
   #:type-universe
   #:equiv->path
   #:path->equiv
   #:equiv-transport
   #:univalence-transport
   #:homotopy-pullback-value
   #:homotopy-pullback-value-left
   #:homotopy-pullback-value-right
   #:homotopy-pullback-value-path
   #:make-homotopy-pullback-value
   #:homotopy-pullback-type
   #:homotopy-pullback-left
   #:homotopy-pullback-right
   #:homotopy-pullback-path
   #:pointed-equivalence
   #:pointed-equivalence-source
   #:pointed-equivalence-target
   #:pointed-equivalence-equivalence
   #:pointed-equivalence-forward-map
   #:pointed-equivalence-backward-map
   #:make-pointed-equivalence
   #:inverse-pointed-equivalence
   #:compose-pointed-equivalences
   #:pointed-equivalence-loop-map

   ;; Dependent products / sums
   #:sigma-value
   #:sigma-value-base
   #:sigma-value-witness
   #:sigma-value-fiber-value
   #:make-sigma-value
   #:sigma-value-in-family-p
   #:sigma-type
   #:pi-function
   #:pi-function-family
   #:pi-function-function
   #:pi-function-checker
   #:make-pi-function
   #:pi-apply
   #:pi-function-in-family-p
   #:pi-type
   #:pi-extensional-path

   ;; Quotients / truncation
   #:hott-quotient
   #:hott-quotient-base
   #:hott-quotient-relation
   #:hott-quotient-canonicalize
   #:hott-quotient-witness
   #:hott-quotient-type
   #:make-hott-quotient
   #:quotient-value
   #:quotient-value-quotient
   #:quotient-value-representative
   #:quotient-value-canonical
   #:quotient-value-witness
   #:make-quotient-value
   #:quotient-value-in-quotient-p
   #:quotient-related-p
   #:quotient-path
   #:set-truncation
   #:trunc-value
   #:trunc-value-base
   #:trunc-value-value
   #:trunc-value-witness
   #:trunc-value-in-type-p
   #:propositional-truncation
   #:make-trunc-value
   #:trunc-path
   #:connected-map-witness
   #:connected-map-witness-source
   #:connected-map-witness-target
   #:connected-map-witness-function
   #:connected-map-witness-fiber-witness-fn
   #:make-connected-map-witness
   #:connected-fiber-type
   #:connected-fiber-proposition
   #:connected-fiber-witness-for
   #:connected-on-p
   #:embedding-map-witness
   #:embedding-map-witness-source
   #:embedding-map-witness-target
   #:embedding-map-witness-function
   #:embedding-map-witness-fiber-path-fn
   #:make-embedding-map-witness
   #:embedding-fiber-type
   #:embedding-fiber-path
   #:embedding-on-p
   #:equiv-from-connected-embedding

   ;; Higher inductive witnesses
   #:higher-inductive-type
   #:higher-inductive-type-name
   #:higher-inductive-type-base-type
   #:higher-inductive-type-point-constructors
   #:higher-inductive-type-path-constructors
   #:hit-eliminator
   #:hit-eliminator-hit
   #:hit-eliminator-target
   #:hit-eliminator-point-actions
   #:hit-eliminator-path-actions
   #:make-higher-inductive-type
   #:hit-value
   #:hit-value-type
   #:hit-value-constructor
   #:hit-value-arguments
   #:make-hit-value
   #:hit-path
   #:make-hit-eliminator
   #:hit-eliminate-value
   #:hit-eliminate-path
   #:homotopy-pushout
   #:homotopy-pushout-hit
   #:homotopy-pushout-left-type
   #:homotopy-pushout-right-type
   #:homotopy-pushout-base-type
   #:homotopy-pushout-left-map
   #:homotopy-pushout-right-map
   #:make-homotopy-pushout
   #:homotopy-pushout-type
   #:pushout-left
   #:pushout-right
   #:pushout-glue
   #:pushout-recursion
   #:homotopy-cofiber
   #:homotopy-cofiber-source
   #:homotopy-cofiber-target
   #:homotopy-cofiber-function
   #:homotopy-cofiber-pushout
   #:make-homotopy-cofiber
   #:homotopy-cofiber-type
   #:cofiber-include
   #:cofiber-basepoint
   #:cofiber-glue
   #:pointed-cofiber
   #:pointed-cofiber-map
   #:pointed-cofiber-cofiber
   #:pointed-cofiber-pointed-type
   #:pointed-cofiber-include-map
   #:pointed-cofiber-collapse-path
   #:make-pointed-cofiber
   #:pointed-cofiber-type
   #:pointed-cofiber-basepoint
   #:pointed-cofiber-include
   #:pointed-cofiber-glue
   #:pointed-fiber
   #:pointed-fiber-map
   #:pointed-fiber-fiber-type
   #:pointed-fiber-pointed-type
   #:pointed-fiber-inclusion-map
   #:pointed-fiber-basepoint
   #:make-pointed-fiber
   #:pointed-fiber-type
   #:pointed-fiber-basepoint-value
   #:pointed-fiber-include
   #:pointed-nullhomotopy
   #:pointed-nullhomotopy-map
   #:pointed-nullhomotopy-homotopy-fn
   #:make-pointed-nullhomotopy
   #:pointed-nullhomotopy-path
   #:pointed-fiber-sequence
   #:pointed-fiber-sequence-map
   #:pointed-fiber-sequence-fiber
   #:pointed-fiber-sequence-inclusion-map
   #:pointed-fiber-sequence-composite-map
   #:pointed-fiber-sequence-nullhomotopy
   #:make-pointed-fiber-sequence
   #:hott-product-value
   #:hott-product-value-left
   #:hott-product-value-right
   #:make-hott-product-value
   #:hott-product-type
   #:hott-product-left
   #:hott-product-right
   #:homotopy-join
   #:homotopy-join-left-type
   #:homotopy-join-right-type
   #:homotopy-join-product-type
   #:homotopy-join-pushout
   #:make-homotopy-join
   #:homotopy-join-type
   #:join-left
   #:join-right
   #:join-glue
   #:pointed-wedge
   #:pointed-wedge-left
   #:pointed-wedge-right
   #:pointed-wedge-pushout
   #:make-pointed-wedge
   #:pointed-wedge-type
   #:wedge-left
   #:wedge-right
   #:wedge-basepoint
   #:wedge-glue
   #:pointed-smash
   #:pointed-smash-left
   #:pointed-smash-right
   #:pointed-smash-product-type
   #:pointed-smash-wedge
   #:pointed-smash-inclusion
   #:pointed-smash-cofiber
   #:make-pointed-smash
   #:pointed-smash-type
   #:smash-pair
   #:smash-basepoint
   #:smash-collapse-left
   #:smash-collapse-right
   #:circle-recursion
   #:circle-type
   #:circle-base
   #:circle-loop
   #:interval-recursion
   #:interval-type
   #:interval-left
   #:interval-right
   #:interval-segment
   #:suspension-type
   #:suspension-type-p
   #:suspension-base
   #:suspension-hit
   #:suspension-north
   #:suspension-south
   #:suspension-meridian
   #:suspension-recursion
   #:pointed-suspension
   #:pointed-suspension-pointed
   #:pointed-suspension-suspension
   #:pointed-suspension-pointed-type
   #:make-pointed-suspension
   #:pointed-suspension-type
   #:pointed-suspension-basepoint
   #:pointed-suspension-north
   #:pointed-suspension-south
   #:pointed-suspension-meridian
   #:pointed-suspension-map
   #:pointed-suspension-map-p
   #:pointed-suspension-map-base-map
   #:pointed-suspension-map-source
   #:pointed-suspension-map-target
   #:pointed-suspension-map-pointed-map
   #:make-pointed-suspension-map
   #:pointed-suspension-map-meridian
   #:pointed-suspension-recursion
   #:pointed-suspension-recursion-p
   #:pointed-suspension-recursion-source
   #:pointed-suspension-recursion-target
   #:pointed-suspension-recursion-suspension
   #:pointed-suspension-recursion-loop-action
   #:pointed-suspension-recursion-recursor
   #:pointed-suspension-recursion-pointed-map
   #:pointed-suspension-recursion-transpose-map
   #:make-pointed-suspension-recursion
   #:pointed-suspension-recursion-meridian
   #:sphere-type

   ;; Truncation levels
   #:+contractible+
   #:+proposition+
   #:+set+
   #:+groupoid+
   #:truncation-level-p
   #:truncation<=))

(in-package #:rosette-hott-core)
