;;;; tests.lisp --- tests for rosette-tool-envelope.

(defpackage #:rosette-tool-envelope/tests
  (:use #:cl #:rosette-tool-envelope #:rosette-assert-core)
  (:export #:run-all-tests))

(in-package #:rosette-tool-envelope/tests)

(defun run-all-tests ()
  (with-test-run (run "rosette-tool-envelope")
    (let* ((env (ok-envelope :data '(:value 42)
                             :metadata '(:source :unit)
                             :warnings :rounded))
           (plist (tool-envelope->plist env)))
      (check run (tool-envelope-p env) "constructor returns envelope")
      (check run (tool-envelope-ok env) "ok-envelope is successful")
      (check run (eq (tool-envelope-status env) :ok)
             "ok-envelope defaults to OK status")
      (check run (equal (tool-envelope-data env) '(:value 42))
             "tool-envelope-data returns payload")
      (check run (equal (tool-envelope-metadata env) '(:source :unit))
             "tool-envelope-metadata returns metadata plist")
      (check run (eq (getf plist :status) :ok) "plist carries status")
      (check run (equal plist
                        '(:ok t
                          :status :ok
                          :data (:value 42)
                          :metadata (:source :unit)
                          :warnings (:rounded)))
             "tool-envelope->plist returns the canonical envelope shape")
      (check run (equal (getf plist :warnings) '(:rounded))
             "single warning is normalized to list"))
    (let* ((env (make-tool-envelope :ok t :data :payload))
           (plist (tool-envelope->plist env)))
      (check run (eq (tool-envelope-status env) :ok)
             "make-tool-envelope defaults true OK to status OK")
      (check run (null (tool-envelope-metadata env))
             "omitted metadata normalizes to NIL")
      (check run (null (tool-envelope-warnings env))
             "omitted warnings normalize to NIL")
      (check run (equal plist
                        '(:ok t :status :ok :data :payload
                          :metadata nil :warnings nil))
             "minimal successful envelope serializes canonically"))
    (let* ((env (make-tool-envelope :ok nil :data :failure))
           (plist (tool-envelope->plist env)))
      (check run (not (tool-envelope-ok env))
             "make-tool-envelope records false OK flag")
      (check run (eq (tool-envelope-status env) :error)
             "make-tool-envelope defaults false OK to status ERROR")
      (check run (eq (getf plist :data) :failure)
             "canonical plist preserves failure payload"))
    (let ((env (merge-envelope-warning
                (error-envelope :status :failed :warnings '(:first))
                :second)))
      (check run (not (tool-envelope-ok env)) "error-envelope is unsuccessful")
      (check run (eq (tool-envelope-status env) :failed) "error status is preserved")
      (check run (equal (tool-envelope-warnings env) '(:first :second))
             "warning merge appends"))
    (let* ((base (ok-envelope :data 7
                              :metadata '(:phase :baseline)
                              :warnings '(:first)))
           (merged (merge-envelope-warning base :second)))
      (check run (not (eq base merged))
             "merge-envelope-warning returns a fresh envelope")
      (check run (tool-envelope-ok merged)
             "warning merge preserves OK flag")
      (check run (= (tool-envelope-data merged) 7)
             "warning merge preserves data")
      (check run (equal (tool-envelope-metadata merged) '(:phase :baseline))
             "warning merge preserves metadata")
      (check run (equal (tool-envelope-warnings base) '(:first))
             "warning merge does not mutate original envelope")
      (check run (equal (tool-envelope-warnings merged) '(:first :second))
             "warning merge appends warning in order"))
    (let ((env (error-envelope :data '(:why :bad)
                               :metadata '(:source :unit)
                               :warnings nil)))
      (check run (not (tool-envelope-ok env))
             "error-envelope defaults to unsuccessful")
      (check run (eq (tool-envelope-status env) :error)
             "error-envelope defaults to ERROR status")
      (check run (equal (tool-envelope-data env) '(:why :bad))
             "error-envelope preserves payload")
      (check run (null (tool-envelope-warnings env))
             "NIL warnings stay NIL"))
    (let* ((metadata (list :source :unit))
           (warnings (list :first))
           (env (ok-envelope :metadata metadata :warnings warnings)))
      (setf (second metadata) :mutated
            (first warnings) :mutated)
      (check run (equal (tool-envelope-metadata env) '(:source :unit))
             "constructor copies metadata plist")
      (check run (equal (tool-envelope-warnings env) '(:first))
             "constructor copies warning list")
      (let ((plist (tool-envelope->plist env)))
        (setf (getf (getf plist :metadata) :source) :plist-mutated
              (first (getf plist :warnings)) :plist-mutated)
        (check run (equal (tool-envelope-metadata env) '(:source :unit))
               "plist metadata is isolated from envelope")
        (check run (equal (tool-envelope-warnings env) '(:first))
               "plist warnings are isolated from envelope")))
    (check run
           (handler-case
               (progn (make-tool-envelope :ok :yes) nil)
             (error () t))
           "ok must be boolean")
    (check run
           (handler-case
               (progn (make-tool-envelope :ok t :status 'ok) nil)
             (error () t))
           "status must be a keyword")
    (check run
           (handler-case
               (progn (ok-envelope :metadata '(:bad)) nil)
             (error () t))
           "metadata must be a plist")
    (check run
           (handler-case
               (progn (ok-envelope :metadata '(1 :bad)) nil)
             (error () t))
           "metadata keys must be symbols")))
