;;;; fbscene.lisp --- the seL4 fb_scene.txt bridge + render fingerprint.
;;;;
;;;; scene->fb-scene-text LOWERS the Face-A superset (fill-rect -> hlines,
;;;; text -> lines) to the size/clear/line vocabulary the UNMODIFIED rosette_fb.c
;;;; consumes; fb-scene-text->scene reads that flat subset back.  On the flat
;;;; FACE-A (size|clear|line) subset the round-trip is the identity, so the
;;;; IR is a faithful superset of fb_scene.txt.
;;;;
;;;; Emission assumes clips do not cut geometry (the C brick has no clip
;;;; stack); layout emits clips at box bounds that bound but never cut, and
;;;; the immediate-mode subset used for emission contains no partial-opacity
;;;; layers (those are composited host-side by compose-layers).

(in-package #:rosette-scene-ir)

;;; ---- emit ----

(defun %op->fb-lines (op)
  "Lower one op to a list of fb_scene.txt line strings (size/clear/line
vocabulary)."
  (ecase (car op)
    (:clear (destructuring-bind (r g b) (cdr op)
              (list (format nil "clear ~d ~d ~d" r g b))))
    (:line (destructuring-bind (x0 y0 x1 y1 r g b th a) (cdr op)
             (list (format nil "line ~d ~d ~d ~d ~d ~d ~d ~d ~d"
                           x0 y0 x1 y1 r g b th a))))
    (:fill-rect (destructuring-bind (x y w h r g b a) (cdr op)
                  (loop for row below h
                        collect (format nil "line ~d ~d ~d ~d ~d ~d ~d 1 ~d"
                                        x (+ y row) (+ x w -1) (+ y row) r g b a))))
    (:text (mapcan #'%op->fb-lines (text->lines op)))
    (:blit (error "scene->fb-scene-text: (:blit ...) is not in the flat C vocabulary"))))

(defun scene->fb-scene-text (scene)
  "Render SCENE to the fb_scene.txt string the freestanding seL4 renderer
consumes (size + clear/line).  Flattens the immediate-mode tree, drops the
non-cutting clip markers, and lowers the Face-A superset."
  (let* ((s (if (scene-p scene) scene (parse-scene scene))))
    (multiple-value-bind (w h) (scene-size s)
      (with-output-to-string (out)
        (format out "# generated by rosette-scene-ir scene->fb-scene-text~%")
        (format out "size ~d ~d~%" w h)
        (dolist (op (flatten-scene s))
          (case (car op)
            ((:clip-push :clip-pop) nil) ; C has no clip stack
            (t (dolist (ln (%op->fb-lines op))
                 (write-line ln out)))))))))

;;; ---- parse ----

(defun %split-ws (line)
  (let ((toks '()) (start nil))
    (loop for i from 0 below (length line)
          for ch = (char line i)
          do (if (member ch '(#\Space #\Tab))
                 (when start (push (subseq line start i) toks) (setf start nil))
                 (unless start (setf start i)))
          finally (when start (push (subseq line start) toks)))
    (nreverse toks)))

(defun fb-scene-text->scene (text)
  "Parse an fb_scene.txt string (size/clear/line) back into a canonical flat
scene: (:scene (:size W H) (:group (:draw (:clear ...)) (:draw (:line ...)) ...))."
  (let ((w nil) (h nil) (draws '()))
    (with-input-from-string (in text)
      (loop for line = (read-line in nil nil) while line
            for toks = (%split-ws line)
            when (and toks (not (char= (char (first toks) 0) #\#)))
              do (let ((nums (mapcar (lambda (tk) (parse-integer tk)) (rest toks))))
                   (cond
                     ((string= (first toks) "size")
                      (setf w (first nums) h (second nums)))
                     ((string= (first toks) "clear")
                      (push (list :draw (cons :clear nums)) draws))
                     ((string= (first toks) "line")
                      (push (list :draw (cons :line nums)) draws))
                     (t (error "fb-scene-text->scene: unknown line ~S" line))))))
    (unless (and w h) (error "fb-scene-text->scene: missing size"))
    (parse-scene (list :scene (list :size w h) (cons :group (nreverse draws))))))

;;; ---- fingerprint (host-stable; no floats on the emit path) ----

(defun frame-fingerprint (frame)
  "FNV-1a 64-bit hash of FRAME's pixel bytes -- a replay/regression handle."
  (let ((hash 14695981039346656037) (px (frame-pixels frame)))
    (declare (type (unsigned-byte 64) hash))
    (loop for b across px do
      (setf hash (logand #xffffffffffffffff
                         (* (logxor hash b) 1099511628211))))
    hash))

(defun scene-fingerprint (scene &key surfaces)
  "Layout-independent hash of the rendered frame of SCENE."
  (frame-fingerprint (render-scene scene :surfaces surfaces)))
