;;;; tests.lisp --- tests for rosette-scalar-core.

(defpackage #:rosette-scalar-core/tests
  (:use #:cl #:rosette-scalar-core #:rosette-assert-core)
  (:export #:run-all-tests))

(in-package #:rosette-scalar-core/tests)

(defun run-all-tests ()
  (with-test-run (run "rosette-scalar-core")
    (check run (float-kind-p :f64) ":f64 is a supported float kind")
    (check run (not (float-kind-p :fixnum)) ":fixnum is not a supported float kind")
    (check run (eq (float-kind-type :f64) 'double-float) ":f64 maps to double-float")
    (check run (eq (float-kind-type :f32) 'single-float) ":f32 maps to single-float")
    (check run (typep (float-kind-zero :f64) 'double-float) ":f64 zero is double-float")
    (check run (= (float-kind-zero :f64) 0d0) ":f64 zero has additive identity value")
    (check run (typep (float-kind-one :f32) 'single-float) ":f32 one is single-float")
    (check run (= (float-kind-one :f32) 1f0) ":f32 one has multiplicative identity value")
    (check run (typep (float-kind-pi :f64) 'double-float) ":f64 pi is double-float")
    (check run (typep (float-kind-pi :f32) 'single-float) ":f32 pi is single-float")
    (check run (= (float-kind-bits :f64) 64) ":f64 exposes bit width")
    (check run (= (float-kind-bits :f32) 32) ":f32 exposes bit width")
    (check run (= (float-kind-bytes :f64) 8) ":f64 exposes byte width")
    (check run (= (float-kind-bytes :f32) 4) ":f32 exposes byte width")
    (check run (= (float-kind-bytes :f64) (/ (float-kind-bits :f64) 8))
           "float-kind-bytes is derived from float-kind-bits for f64")
    (check run (= (float-kind-bytes :f32) (/ (float-kind-bits :f32) 8))
           "float-kind-bytes is derived from float-kind-bits for f32")
    (check run (typep (float-kind-tolerance :f64) 'double-float) ":f64 tolerance is double-float")
    (check run (typep (float-kind-tolerance :f32) 'single-float) ":f32 tolerance is single-float")
    (check run (< (float-kind-tolerance :f64) (float-kind-tolerance :f32))
           ":f64 default tolerance is tighter than :f32")
    (check run (eq (getf (float-kind-descriptor :f64) :storage) :ieee-binary64)
           ":f64 descriptor exposes storage")
    (check run (= (getf (float-kind-descriptor :f32) :bits) 32)
           ":f32 descriptor exposes bit width")
    (let ((descriptor (float-kind-descriptor :f64)))
      (check run (and (eq (getf descriptor :kind) :f64)
                      (eq (getf descriptor :type) (float-kind-type :f64))
                      (= (getf descriptor :bits) (float-kind-bits :f64))
                      (= (getf descriptor :bytes) (float-kind-bytes :f64))
                      (= (getf descriptor :zero) (float-kind-zero :f64))
                      (= (getf descriptor :one) (float-kind-one :f64))
                      (= (getf descriptor :tolerance) (float-kind-tolerance :f64)))
             ":f64 descriptor is consistent with float-kind accessors"))
    (let ((descriptor (float-kind-descriptor :f32)))
      (check run (and (eq (getf descriptor :kind) :f32)
                      (eq (getf descriptor :type) (float-kind-type :f32))
                      (= (getf descriptor :bits) (float-kind-bits :f32))
                      (= (getf descriptor :bytes) (float-kind-bytes :f32))
                      (= (getf descriptor :zero) (float-kind-zero :f32))
                      (= (getf descriptor :one) (float-kind-one :f32))
                      (= (getf descriptor :tolerance) (float-kind-tolerance :f32)))
             ":f32 descriptor is consistent with float-kind accessors"))
    (check run (eq (scalar-kind-of 1d0) :f64) "scalar-kind-of detects f64")
    (check run (eq (scalar-kind-of 1f0) :f32) "scalar-kind-of detects f32")
    (check run (eq (scalar-kind-of 1/3) :exact-rational)
           "scalar-kind-of preserves exact rationals")
    (check run (typep (as-float-kind :f64 1) 'double-float) "as-float-kind returns f64")
    (check run (typep (as-float-kind :f32 1) 'single-float) "as-float-kind returns f32")
    (check run (= (as-float-kind :f64 3/2) 1.5d0)
           "as-float-kind coerces exact rationals to f64")
    (check run (= (as-float-kind :f32 3/2) 1.5f0)
           "as-float-kind coerces exact rationals to f32")
    (check run (handler-case (progn (as-float-kind :bad 1) nil)
                 (error () t))
           "as-float-kind rejects unsupported kinds")
    (with-float-kind (:f32)
      (check run (typep (f 2) 'single-float) "with-float-kind F coerces values")
      (check run (= (f-zero) 0f0) "with-float-kind F-ZERO returns the kind zero")
      (check run (= (f-one) 1f0) "with-float-kind F-ONE returns the kind one"))
    (with-float-kind (:f64)
      (check run (and (typep (f 2) 'double-float)
                      (= (+ (f-one) (f-zero)) 1d0))
             "with-float-kind binds f64 helpers coherently"))
    (check run (typep (as-f64 1) 'double-float) "as-f64 returns double-float")
    (check run (typep (as-f32 1) 'single-float) "as-f32 returns single-float")
    (check run (= (as-f64 3/2) 1.5d0) "as-f64 coerces exact rationals")
    (check run (= (as-f32 3/2) 1.5f0) "as-f32 coerces exact rationals")
    (check run (= (f64-add 1 2) 3d0) "f64-add coerces before adding")
    (check run (= (f64-sub 5 2) 3d0) "f64-sub coerces before subtracting")
    (check run (= (f64-mul 3 2) 6d0) "f64-mul coerces before multiplying")
    (check run (= (f64-sub (f64-add 1 2) 2) 1d0)
           "f64-sub inverts f64-add on the right operand")
    (check run (= (f64-ratio (f64-mul 3 2) 2) 3d0)
           "f64-ratio inverts f64-mul on the denominator")
    (check run (and (= (f64-ratio 1 2) 0.5d0)
                    (typep (f64-ratio 1 2) 'double-float))
           "f64-ratio divides after double-float coercion")
    (check run (not (f64-distance< 1 1 0d0))
           "f64-distance< is strict at zero tolerance")
    (check run (f64-distance< 1 1.000000000001d0 1d-9)
           "f64-distance< compares after double-float coercion")
    (check run (not (f64-distance< 1 1.01d0 1d-9))
           "f64-distance< rejects distant values")
    (check run (typep (as-f64-pi) 'double-float) "as-f64-pi returns double-float")
    (check run (= (as-f64-pi) (float-kind-pi :f64)) "as-f64-pi agrees with float-kind-pi")
    (check run (approx= 1 1d0) "integer/double equality")
    (check run (approx= 1d0 (+ 1d0 (/ +default-tolerance+ 2d0))) "within tolerance")
    (check run (approx= 1d0 (+ 1d0 +default-tolerance+) +default-tolerance+)
           "approx= includes the tolerance boundary")
    (check run (not (approx= 1d0 1.01d0)) "outside tolerance")
    (check run (eq (approx= 1d0 1.00001d0 1d-4)
                   (near= 1d0 1.00001d0 1d-4))
           "near= and approx= agree on explicit tolerance")
    (check run (near= 1d0 (+ 1d0 (/ +default-tolerance+ 2d0))) "near= aliases approx=")
    (check run (not (near= 1d0 1.01d0)) "near= outside tolerance")))
