;;;; tests.lisp --- tests for rosette-assert-core.

(defpackage #:rosette-assert-core/tests
  (:use #:cl #:rosette-assert-core)
  (:export #:run-all-tests))

(in-package #:rosette-assert-core/tests)

(defun run-all-tests ()
  (let ((assertions 0))
    (flet ((ok (condition message)
             (incf assertions)
             (assert-true condition message))
           (signals-error (thunk message)
             (incf assertions)
             (let ((signaled nil))
               (handler-case (funcall thunk)
                 (error () (setf signaled t)))
               (assert-true signaled message))))
      (ok (null (assert-true t "true")) "assert-true passes")
      (signals-error (lambda () (assert-true nil "false"))
                     "assert-true rejects nil")
      (ok (null (assert= 2 2 "equal")) "assert= passes")
      (signals-error (lambda () (assert= 2 3 "not equal"))
                     "assert= rejects unequal numbers")
      (ok (null (assert-close 1d0 1.0d0 "close")) "assert-close passes")
      (ok (null (assert-close 1d0 (+ 1d0 5d-4) "custom close" 1d-3))
          "assert-close honors custom tolerance")
      (signals-error (lambda () (assert-close 1d0 1.1d0 "not close"))
                     "assert-close rejects values outside default tolerance")
      (signals-error (lambda () (assert-close 1d0 (+ 1d0 2d-3)
                                             "outside custom" 1d-3))
                     "assert-close rejects values outside custom tolerance")
      (let ((a (make-array 2 :initial-contents '(1d0 2d0)))
            (b (make-array 2 :initial-contents '(1d0 2d0))))
        (ok (null (assert-array-close a b "array close"))
            "assert-array-close passes"))
      (let ((a (make-array 2 :initial-contents '(1d0 2d0)))
            (b (make-array 2 :initial-contents '(1d0 2.0005d0))))
        (ok (null (assert-array-close a b "array custom close" 1d-3))
            "assert-array-close honors custom tolerance"))
      (let ((a (make-array 2 :initial-contents '(1d0 2d0)))
            (b (make-array 3 :initial-contents '(1d0 2d0 3d0))))
        (signals-error (lambda () (assert-array-close a b "array size"))
                       "assert-array-close rejects size mismatch"))
      (let ((a (make-array 2 :initial-contents '(1d0 2d0)))
            (b (make-array 2 :initial-contents '(1d0 3d0))))
        (signals-error (lambda () (assert-array-close a b "array element"))
                       "assert-array-close rejects distant element"))
      (let ((run (make-test-run "manual")))
        (ok (string= (test-run-name run) "manual") "make-test-run stores name")
        (ok (zerop (test-run-assertions run))
            "make-test-run starts with zero assertions")
        (ok (zerop (test-run-failures run))
            "make-test-run starts with zero failures")
        (ok (eq (record-test run t "pass") t) "record-test returns true result")
        (ok (= (test-run-assertions run) 1)
            "record-test counts passing assertion")
        (ok (zerop (test-run-failures run))
            "record-test leaves failures unchanged on pass")
        (ok (null (record-test run nil "fail")) "record-test returns false result")
        (ok (= (test-run-assertions run) 2)
            "record-test counts failing assertion")
        (ok (= (test-run-failures run) 1)
            "record-test counts failure"))
      (let ((run (make-test-run "check-macro")))
        (ok (check run (= 1 1) "check pass") "check records true form")
        (ok (null (check run (= 1 2) "check fail")) "check records false form")
        (ok (= (test-run-assertions run) 2) "check counts both forms")
        (ok (= (test-run-failures run) 1) "check counts false form as failure")
        (signals-error (lambda () (finish-test-run run))
                       "finish-test-run signals on recorded failure"))
      (ok (= 2
             (with-test-run (run "rosette-assert-core/nested")
               (check run t "first")
               (check run (= 2 2) "second")))
          "with-test-run returns assertion count")
      (signals-error (lambda ()
                       (with-test-run (run "rosette-assert-core/failing")
                         (check run nil "failing check")))
                     "with-test-run propagates finish failure"))
    (format t "rosette-assert-core: ~D assertions, 0 failures~%" assertions)
    assertions))
