;;;; tests.lisp --- tests for rosette-byte-core.

(defpackage #:rosette-byte-core/tests
  (:use #:cl #:rosette-byte-core)
  (:export #:run-all-tests))

(in-package #:rosette-byte-core/tests)

(defun assert-true (condition message)
  (unless condition
    (error "Assertion failed: ~A" message)))

(defun frozen-original-coerce-byte-element (value)
  (etypecase value
    (integer (logand #xff value))
    (character (logand #xff (char-code value)))))

(defun frozen-original-coerce-byte-vector (data)
  (let* ((n (length data))
         (out (make-byte-vector n)))
    (etypecase data
      (string
       (loop for i below n
             do (setf (aref out i)
                      (logand #xff (char-code (char data i))))))
      (vector
       (loop for i below n
             do (setf (aref out i)
                      (frozen-original-coerce-byte-element
                       (aref data i))))))
    out))

(defun random-byte-vector (length state)
  (let ((bytes (make-byte-vector length)))
    (dotimes (i length bytes)
      (setf (aref bytes i) (random 256 state)))))

(defun coerce-byte-vector-oracle-p ()
  (let ((state (sb-ext:seed-random-state 20260612)))
    (loop repeat 1000
          for length = (random 1024 state)
          for data = (random-byte-vector length state)
          always (equalp (frozen-original-coerce-byte-vector data)
                         (coerce-byte-vector data)))))

(defun run-all-tests ()
  (let ((assertions 0))
    (flet ((ok (condition message)
             (incf assertions)
             (assert-true condition message)))
      (let ((bytes (coerce-byte-vector "ABC")))
        (ok (typep bytes 'byte-vector) "string coercion returns byte-vector")
        (ok (equalp bytes #(65 66 67)) "string coercion preserves ASCII bytes")
        (setf (aref bytes 0) 90)
        (ok (equalp (coerce-byte-vector "ABC") #(65 66 67))
            "string coercion returns a fresh byte-vector"))
      (ok (equalp (coerce-byte-vector (string (code-char #x141)))
                  #(65))
          "string coercion uses low 8 bits of char-code")
      (let ((bytes (make-byte-vector 3 :initial-element 257)))
        (ok (typep bytes 'byte-vector) "make-byte-vector returns byte-vector")
        (ok (equalp bytes #(1 1 1)) "make-byte-vector clips initial byte"))
      (ok (= (length (make-byte-vector 0)) 0)
          "make-byte-vector supports empty byte vectors")
      (ok (equalp (make-byte-vector 2 :initial-element -1) #(255 255))
          "make-byte-vector clips negative initial byte to low 8 bits")
      (ok (equalp (coerce-byte-vector #(0 255 256 -1)) #(0 255 0 255))
          "integer vector coercion clips to low 8 bits")
      (let* ((source #(1 2 3))
             (bytes (coerce-byte-vector source)))
        (setf (aref bytes 0) 9)
        (ok (equalp source #(1 2 3))
            "vector coercion returns a fresh copy"))
      (ok (coerce-byte-vector-oracle-p)
          "byte-vector coercion oracle: frozen original on 1000 random byte vectors")
      (ok (equalp (coerce-byte-vector (vector #\A #\B)) #(65 66))
          "character vector coercion uses char-code")
      (ok (equalp (coerce-byte-vector (vector #\A 256 #\B -1))
                  #(65 0 66 255))
          "mixed character/integer vector coercion uses low 8 bits")
      (dolist (fixture '(#() #(0) #(0 1) #(0 1 2)
                           #(0 1 2 3) #(255 254 253 252 251)))
        (let ((encoded (base64-encode-bytes fixture)))
          (ok (equalp fixture (base64-decode-bytes encoded))
              "canonical Base64 round-trips bytes")
          (ok (string= encoded
                       (base64-encode-bytes
                        (base64-decode-bytes encoded)))
              "canonical Base64 is a fixed point")))
      (ok (equalp #(77 97 110)
                  (base64-decode-bytes (format nil " T W F u~%")))
          "Base64 decoder optionally ignores transport whitespace")
      (dolist (malformed '("A" "AA=A" "A===" "AB==" "AAB=" "AA?="))
        (ok (handler-case
                (progn (base64-decode-bytes malformed) nil)
              (error () t))
            "Base64 decoder rejects malformed or noncanonical input"))
      (let ((windows (byte-windows #(1 2 3 4 5) 2 :stride 2)))
        (ok (and (= (length windows) 3)
                 (equalp (aref windows 0) #(1 2))
                 (equalp (aref windows 2) #(5)))
            "byte-windows keeps final partial window by default")
        (setf (aref (aref windows 0) 0) 99)
        (ok (equalp (aref windows 1) #(3 4))
            "byte-windows returns independent fresh windows"))
      (let ((windows (byte-windows #(1 2 3 4) 3 :stride 1)))
        (ok (and (= (length windows) 4)
                 (equalp (aref windows 0) #(1 2 3))
                 (equalp (aref windows 1) #(2 3 4))
                 (equalp (aref windows 3) #(4)))
            "byte-windows supports overlapping stride-one windows"))
      (ok (= (length (byte-windows #(1 2 3 4 5) 2 :stride 2 :drop-tail t)) 2)
          "byte-windows can drop final partial window")
      (ok (= (length (byte-windows #() 4)) 0)
          "byte-windows of empty input has no windows")
      (ok (= (bits-to-bytes 0) 0) "bits-to-bytes maps zero bits to zero bytes")
      (ok (= (bits-to-bytes 8) 1) "bits-to-bytes keeps exact byte boundaries")
      (ok (= (bits-to-bytes 9) 2) "bits-to-bytes rounds up")
      (ok (= (bytes-to-bits 2) 16) "bytes-to-bits multiplies by 8")
      (ok (= (bytes-to-bits (bits-to-bytes 17)) 24)
          "bits-to-bytes and bytes-to-bits round-trip to the byte ceiling")
      (ok (= (low-nibble #xab) #xb) "low-nibble extracts low four bits")
      (ok (= (low-nibble #x1ab) #xb) "low-nibble masks to low four bits")
      (ok (= (high-nibble #xab) #xa) "high-nibble extracts high four bits")
      (ok (= (high-nibble #x1ab) #xa) "high-nibble ignores bits above the byte")
      (ok (= (pack-nibbles #xb #xa) #xab)
          "pack-nibbles combines low and high nibbles")
      (ok (= (pack-nibbles #x1b #x2a) #xab)
          "pack-nibbles masks inputs to low nibbles")
      (let ((byte (pack-nibbles 3 12)))
        (ok (= (low-nibble byte) 3)
            "pack-nibbles round-trips the low nibble")
        (ok (= (high-nibble byte) 12)
            "pack-nibbles round-trips the high nibble")))
    (format t "rosette-byte-core: ~D assertions, 0 failures~%" assertions)
    assertions))
