(in-package #:rosette-sexpr-dag)

(defun shared-subdag-shape (sexp)
  "Return a coarse syntactic shape for SEXP."
  (cond
    ((%test-harness-p sexp) :test-harness)
    ((%build-metadata-p sexp) :build-metadata)
    ((%equality-policy-fragment-p sexp) :equality-policy)
    ((%array-dimensions-p sexp) :array-dimensions)
    ((%type-spec-p sexp) :type-spec)
    ((%domain-parameter-list-p sexp) :domain-parameter-list)
    ((%macro-binding-spec-p sexp) :macro-binding-spec)
    ((%literal-data-loader-p sexp) :literal-data)
    ((%keyword-default-binding-list-p sexp) :lambda-list-fragment)
    ((and (consp sexp)
          (%proper-list-p sexp)
          (some (lambda (item)
                  (%symbol-name-in-p item '("&key" "&optional" "&rest"
                                            "&body" "&aux")))
                sexp))
     :lambda-list)
    ((and (consp sexp) (%every-proper-list-p #'consp sexp)
          (some (lambda (item) (member (first item) '(&key &optional &rest)))
                sexp))
     :lambda-list-fragment)
    ((or (%sexp-head-name-in-p sexp '("declare" "declaim" "proclaim"))
         (%declaration-spec-p sexp)
         (%typed-slot-spec-p sexp)
         (%slot-option-fragment-p sexp)
         (and (consp sexp) (%every-proper-list-p #'%typed-slot-spec-p sexp))
         (and (consp sexp) (%every-proper-list-p #'%slot-option-fragment-p sexp))
         (and (consp sexp) (%every-proper-list-p #'%declaration-spec-p sexp))
         (and (consp sexp) (%every-proper-list-p #'%optimize-quality-p sexp)))
     :declaration)
    ((and (consp sexp) (%every-proper-list-p #'consp sexp)
          (%every-proper-list-p
           (lambda (item)
             (and (symbolp (first item))
                  (not (eq (symbol-package (first item))
                           (find-package :cl)))))
           sexp))
     :binding-list)
    ((%sexp-head-name-in-p sexp '("defun" "defmacro" "defmethod"))
     :definition)
    ((%sexp-head-name-in-p sexp '("let" "let*" "flet" "labels"))
     :local-computation)
    ((%sexp-head-name-in-p sexp '("loop" "dotimes" "dolist"))
     :iteration)
    ((%sexp-head-name-in-p sexp '("setf" "incf" "decf" "push"))
     :mutation)
    ((or (%quoted-form-p sexp)
         (and (consp sexp) (%every-proper-list-p #'%quoted-form-p sexp))
         (%literal-data-list-p sexp))
     :literal-data)
    ((and (consp sexp) (keywordp (first sexp)))
     :literal-data)
    (t :expression)))

(defun shared-subdag-motif (sexp)
  "Return a reusable architecture motif label for SEXP."
  (let ((shape (shared-subdag-shape sexp)))
    (cond
      ((%compiler-policy-p sexp) :compiler-policy)
      ((%test-harness-p sexp) :test-harness)
      ((%build-metadata-p sexp) :build-metadata)
      ((%equality-policy-fragment-p sexp) :equality-policy)
      ((or (%timing-scaffold-p sexp)
           (%bench-scaffold-p sexp))
       :timing-scaffold)
      ((or (%sexp-contains-symbol-p sexp '("make-double-float-array"
                                           "zeros"
                                           "zeros3"
                                           "simple-array"
                                           "double-float"))
           (and (consp sexp)
                (%proper-list-p sexp)
                (member :element-type sexp :test #'eq)))
       :typed-vector-result)
      ((%sexp-contains-symbol-p sexp '("state-label" "state-values"
                                       "state-weights" "advance-state"
                                       "merge-states"))
       :finite-state-carrier)
      ((%sexp-contains-symbol-p sexp '("periodic-index" "do-grid" "do-grid3"
                                       "mesh-dx" "mesh3-dx"))
       :grid-stencil)
      ((or (%vector-reduction-p sexp)
           (%paired-vector-access-p sexp)
           (%coerced-vector-access-p sexp)
           (%float-accumulator-finalization-p sexp)
           (%vector-element-difference-p sexp))
       :vector-reduction)
      ((%sexp-contains-symbol-p sexp '("certificate" "verify" "witness"
                                       "kkt" "proof"))
       :certificate-shape)
      ((%sexp-contains-symbol-p sexp '("spectrum" "eigenvalue"
                                       "multiplicity" "zeta"))
       :spectrum-table)
      ((%serializer-scaffold-p sexp) :serializer)
      ((%config-scaffold-p sexp) :config-scaffold)
      ((%gpu-pipeline-p sexp) :gpu-pipeline)
      ((%analysis-scaffold-p sexp) :analysis-scaffold)
      ((%reporting-scaffold-p sexp) :reporting-scaffold)
      ((%work-scheduler-p sexp) :work-scheduler)
      ((%byte-buffer-allocator-p sexp) :byte-buffer)
      ((%bit-packing-p sexp) :bit-packing)
      ((%representation-table-p sexp) :representation-table)
      ((%geometry-metric-p sexp) :geometry-metric)
      ((%symbolic-expression-p sexp) :symbolic-expression)
      ((%finite-difference-p sexp) :finite-difference)
      ((eq shape :literal-data) :literal-table)
      ((eq shape :type-spec) :type-metadata)
      ((eq shape :domain-parameter-list) :domain-model)
      ((eq shape :macro-binding-spec) :control-metadata)
      ((eq shape :declaration) :declaration-metadata)
      ((eq shape :iteration) :iteration-kernel)
      ((eq shape :local-computation) :local-computation)
      (t :generic-expression))))
