;;;; package.lisp --- Public API for rosette-process-engineering.

(defpackage #:rosette-process-engineering
  (:use #:cl)
  (:import-from #:rosette-chemical-formula
                #:parse-formula
                #:formula-molecular-weight)
  (:import-from #:rosette-scalar-core
                #:approx=)
  (:export
   #:+default-balance-tolerance+
   #:material-stream
   #:material-stream-p
   #:stream-p
   #:make-stream
   #:stream-name
   #:stream-flows
   #:stream-temperature
   #:stream-pressure
   #:stream-note
   #:stream-components
   #:stream-component-flow
   #:stream-total-flow
   #:stream-scale
   #:stream-with-flow
   #:stream->plist
   #:mix-streams
   #:split-stream
   #:parse-formula
   #:formula-molecular-weight
   #:component
   #:component-p
   #:make-component
   #:component-key
   #:component-formula
   #:component-molecular-weight
   #:component-phase
   #:component-hhv
   #:component-lhv
   #:component-hazard
   #:component-note
   #:component->plist
   #:component-catalog
   #:component-catalog-p
   #:make-component-catalog
   #:component-catalog-with
   #:component-catalog-components
   #:catalog-component
   #:catalog-molecular-weight
   #:*default-component-catalog*
   #:reaction
   #:reaction-p
   #:make-reaction
   #:reaction-name
   #:reaction-stoich
   #:reaction-note
   #:reaction-reactants
   #:reaction-products
   #:reaction-reactant-extent
   #:reaction-extent-limit
   #:reaction-limiting-reactant
   #:reaction-product-theoretical-yield
   #:reaction-balanced-mass-residual
   #:reaction-element-residuals
   #:reaction-element-balanced-p
   #:reaction-balanced-p
   #:reaction->plist
   #:stoichiometric-reactor
   #:biomass-analysis
   #:biomass-analysis-p
   #:make-biomass-analysis
   #:biomass-analysis-moisture
   #:biomass-analysis-ash
   #:biomass-analysis-volatile-matter
   #:biomass-analysis-fixed-carbon
   #:biomass-analysis-carbon
   #:biomass-analysis-hydrogen
   #:biomass-analysis-oxygen
   #:biomass-analysis-nitrogen
   #:biomass-analysis-sulfur
   #:biomass-analysis-hhv
   #:biomass-analysis-lhv
   #:biomass-analysis-note
   #:biomass-dry-fraction
   #:biomass-combustible-fraction
   #:biomass-stream-from-analysis
   #:biomass-analysis->plist
   #:gas-quality
   #:gas-quality-p
   #:gas-quality-from-stream
   #:gas-quality-h2
   #:gas-quality-co
   #:gas-quality-co2
   #:gas-quality-ch4
   #:gas-quality-inerts
   #:gas-quality-total
   #:syngas-module
   #:h2-co-ratio
   #:co2-fraction
   #:inerts-fraction
   #:methanol-theoretical-max
   #:gas-quality->plist
   #:dryer-duty
   #:dryer-output-stream
   #:component-separator
   #:condenser
   #:gas-splitter
   #:solids-separator
   #:distillation-cut
   #:purge-recycle-split
   #:uncertain-parameter
   #:uncertain-parameter-p
   #:make-uncertain-parameter
   #:uncertain-parameter-name
   #:uncertain-parameter-low
   #:uncertain-parameter-base
   #:uncertain-parameter-high
   #:uncertain-parameter-unit
   #:uncertain-parameter-note
   #:uncertain-parameter-value
   #:uncertain-parameter->plist
   #:uncertainty-cases
   #:conversion-reactor
   #:yield-reactor
   #:heat-duty
   #:heat-duty-p
   #:make-heat-duty
   #:heat-duty-name
   #:heat-duty-value
   #:heat-duty-unit
   #:heat-duty-note
   #:heat-duty->plist
   #:heat-balance
   #:heat-balance-p
   #:make-heat-balance
   #:heat-balance-name
   #:heat-balance-duties
   #:heat-balance-unit
   #:heat-balance-tolerance
   #:heat-balance-note
   #:heat-balance-net-duty
   #:heat-balance-demand-total
   #:heat-balance-source-total
   #:heat-balance-closed-p
   #:heat-balance->plist
   #:+carbon-entry-roles+
   #:carbon-entry-role-p
   #:carbon-entry
   #:carbon-entry-p
   #:make-carbon-entry
   #:carbon-entry-name
   #:carbon-entry-value
   #:carbon-entry-unit
   #:carbon-entry-role
   #:carbon-entry-note
   #:carbon-entry->plist
   #:carbon-ledger
   #:carbon-ledger-p
   #:make-carbon-ledger
   #:carbon-ledger-name
   #:carbon-ledger-entries
   #:carbon-ledger-unit
   #:carbon-ledger-tolerance
   #:carbon-ledger-note
   #:carbon-ledger-net-burden
   #:carbon-ledger-role-total
   #:carbon-ledger-role-breakdown
   #:carbon-ledger-improves-p
   #:carbon-ledger->plist
   #:+economic-entry-roles+
   #:economic-entry-role-p
   #:economic-entry
   #:economic-entry-p
   #:make-economic-entry
   #:economic-entry-name
   #:economic-entry-value
   #:economic-entry-unit
   #:economic-entry-role
   #:economic-entry-note
   #:economic-entry->plist
   #:economic-ledger
   #:economic-ledger-p
   #:make-economic-ledger
   #:economic-ledger-name
   #:economic-ledger-entries
   #:economic-ledger-unit
   #:economic-ledger-tolerance
   #:economic-ledger-note
   #:economic-ledger-net-value
   #:economic-ledger-role-total
   #:economic-ledger-role-breakdown
   #:economic-ledger-viable-p
   #:economic-ledger->plist
   #:mass-balance
   #:mass-balance-p
   #:make-mass-balance
   #:mass-balance-name
   #:mass-balance-inputs
   #:mass-balance-outputs
   #:mass-balance-tolerance
   #:mass-balance-note
   #:mass-balance-input-total
   #:mass-balance-output-total
   #:mass-balance-residual
   #:mass-balance-components
   #:mass-balance-component-input-flow
   #:mass-balance-component-output-flow
   #:mass-balance-component-residual
   #:mass-balance-component-residuals
   #:mass-balance-component-closed-p
   #:mass-balance-closed-p
   #:mass-balance->plist))

(in-package #:rosette-process-engineering)
