(defpackage #:rosette-foundation-rewrite/tests
  (:use #:cl #:rosette-foundation-rewrite)
  (:export #:run-all-tests))

(in-package #:rosette-foundation-rewrite/tests)

(defun matrix (rows)
  (make-array (list (length rows) (length (first rows)))
              :initial-contents rows))

(defun signals-error-p (thunk)
  (handler-case
      (progn (funcall thunk) nil)
    (error () t)))

(defun run-all-tests ()
  (let ((j2 (matrix '((0d0 1d0)
                     (0d0 0d0))))
        (j2-alt (matrix '((0d0 0d0)
                         (1d0 0d0))))
        (zero3 (matrix '((0d0 0d0 0d0)
                        (0d0 0d0 0d0)
                        (0d0 0d0 0d0))))
        (non-square (matrix '((0d0 1d0 0d0)
                             (0d0 0d0 0d0))))
        (not-square-zero (matrix '((1d0 0d0)
                                  (0d0 0d0)))))
    (multiple-value-bind (r h) (normal-form-decompose j2)
      (assert (= r 1))
      (assert (= h 0)))
    (multiple-value-bind (r h) (normal-form-decompose zero3)
      (assert (= r 0))
      (assert (= h 3)))
    (assert (equal (normal-form-invariant j2) '(2 . 0)))
    (assert (equal (normal-form-invariant zero3) '(3 . 3)))
    (assert (normal-form-equivalent-p j2 j2-alt))
    (assert (not (normal-form-equivalent-p j2 zero3)))
    (assert (signals-error-p (lambda () (normal-form-decompose non-square))))
    (assert (signals-error-p (lambda () (normal-form-decompose not-square-zero)))))

  (let* ((x (tlc-var 'x))
         (y (tlc-var 'y))
         (id (tlc-lam 'x x))
         (const (tlc-lam 'x (tlc-lam 'z x)))
         (app (tlc-app id y)))
    (assert (eq (tlc-term-kind x) :var))
    (assert (equal (tlc-term-parts x) '(x)))
    (assert (eq (tlc-var-name x) 'x))
    (assert (eq (tlc-lam-param id) 'x))
    (assert (tlc-equal-p (tlc-lam-body id) x))
    (assert (tlc-equal-p (tlc-app-fn app) id))
    (assert (tlc-equal-p (tlc-app-arg app) y))
    (assert (tlc-equal-p (make-tlc-term :var 'x) x))
    (assert (not (tlc-equal-p (tlc-var 'x) (tlc-var 'z))))
    (assert (not (tlc-equal-p (tlc-lam 'x x) (tlc-lam 'z x))))
    (assert (tlc-equal-p (beta-step app) y))
    (assert (null (beta-step y)))
    (assert (tlc-equal-p (normalize app) y))
    (assert (tlc-equal-p (normalize (tlc-app const y))
                         (tlc-lam 'z y)))
    (assert (confluent-p app y))
    (assert (not (confluent-p (tlc-var 'a) (tlc-var 'b))))
    (assert (signals-error-p (lambda () (tlc-var-name id)))))

  (assert (tlc-equal-p (normalize (tlc-app (tlc-lam 'x (tlc-var 'x))
                                           (tlc-var 'y)))
                       (tlc-var 'y)))
  (let* ((self (tlc-lam 'x (tlc-app (tlc-var 'x) (tlc-var 'x))))
         (omega (tlc-app self self))
         (captured nil))
    (handler-case
        (normalize omega :max-iter 3)
      (diverging-omega (c)
        (setf captured c)))
    (assert captured)
    (assert (tlc-equal-p (diverging-omega-term captured) omega)))

  (assert (= (dag-node-count (tlc-app (tlc-var 'x) (tlc-var 'x))) 2))
  (assert (= (dag-node-count (tlc-var 'x)) 1))
  (assert (= (dag-node-count (tlc-lam 'x (tlc-var 'x))) 2))
  (assert (= (shared-dag-node-count (list (tlc-var 'x) (tlc-var 'x))) 1))
  (assert (<= (shared-dag-node-count (list (tlc-var 'x)))
              (shared-dag-node-count (list (tlc-var 'x) (tlc-var 'y)))))
  (let* ((a1 (tlc-var 'x))
         (a2 (tlc-app (tlc-var 'x) (tlc-var 'x)))
         (rank (optimal-axiom-rank (list (cons 'small a1)
                                         (cons 'large a2)))))
    (assert (= (length rank) 2))
    (assert (eq (axiom-rank-entry-name (first rank)) 'large))
    (assert (= (axiom-rank-entry-k-axiom (first rank)) 2))
    (assert (= (axiom-rank-entry-k-combined (first rank))
               (axiom-rank-entry-k-combined (second rank))))
    (assert (= (axiom-rank-entry-k-rest (first rank))
               (- (axiom-rank-entry-k-combined (first rank))
                  (axiom-rank-entry-k-axiom (first rank))))))

  (assert (equal (rosette-foundation-rewrite::set-union-eql '(a b) '(b c a d))
                 '(a b c d)))
  (assert (equal (rosette-foundation-rewrite::set-union-eql '() '(a a b))
                 '(a b)))
  (assert (equal (rosette-foundation-rewrite::list-conjunction-union
                  '((1 . a)) '((1 . a) (1 . b)))
                 '((1 . a) (1 . b))))
  t)
