;;;; tests.lisp --- Tests for rosette-work-scheduler.

(defpackage #:rosette-work-scheduler/tests
  (:use #:cl #:rosette-work-scheduler)
  (:export #:run-all-tests))

(in-package #:rosette-work-scheduler/tests)

(defmacro ok (condition message)
  `(unless ,condition
     (error "FAIL: ~A" ,message)))

(defun batch-names (batches)
  (mapcar (lambda (batch) (mapcar #'work-item-name batch)) batches))

(defun run-all-tests ()
  (let ((assertions 0))
    (flet ((check (condition message)
             (incf assertions)
             (ok condition message)))
      (let ((a (make-work-item :name :a :reads '(:x) :writes '(:y)))
            (b (make-work-item :name :b :reads '(:z) :writes '(:w))))
        (check (work-independent-p a b)
               "disjoint read/write footprints are independent"))
      (let ((a (make-work-item :name :a :writes '(:x)))
            (b (make-work-item :name :b :reads '(:x))))
        (check (not (work-independent-p a b))
               "write/read overlap conflicts")
        (check (eq :write-read (work-conflict-kind (first (work-conflicts a b))))
               "conflict records classify write/read overlap"))
      (let ((t2 (make-work-item :name :t2 :writes '(:q-expansion)
                                :commutes-with '(:t3)))
            (t3 (make-work-item :name :t3 :writes '(:q-expansion))))
        (check (work-independent-p t2 t3)
               "commutativity certificate permits overlapping writes"))
      (let* ((parse (make-work-item :name :parse :writes '(:ast) :cost 1d0))
             (infer (make-work-item :name :infer :reads '(:ast) :writes '(:types)
                                    :depends-on '(:parse) :cost 3d0))
             (emit (make-work-item :name :emit :reads '(:ast) :writes '(:cuda)
                                   :depends-on '(:parse) :cost 4d0))
             (test (make-work-item :name :test :reads '(:types :cuda)
                                   :depends-on '(:infer :emit) :cost 2d0))
             (batches (parallel-batches (list parse infer emit test))))
        (check (equal '((:parse) (:infer :emit) (:test)) (batch-names batches))
               "dependency frontier batches independent middle work"))
      (let* ((a (make-work-item :name :a :writes '(:a) :cost 1d0))
             (b (make-work-item :name :b :depends-on '(:a) :writes '(:b) :cost 1d0))
             (c (make-work-item :name :c :depends-on '(:b) :writes '(:c) :cost 1d0))
             (batches (parallel-batches (list a b c))))
        (check (equal '((:a) (:b) (:c)) (batch-names batches))
               "dependencies completed inside a batch do not unlock same-batch work"))
      (let* ((a (make-work-item :name :a :writes '(:a) :cost 1d0))
             (b (make-work-item :name :b :depends-on '(:a) :writes '(:b) :cost 1d0))
             (good (parallel-batches (list a b))))
        (multiple-value-bind (ok reasons)
            (verify-parallel-plan (list a b) good)
          (check ok "generated batches verify")
          (check (null reasons) "valid schedule has no rejection reasons"))
        (multiple-value-bind (ok reasons)
            (verify-parallel-plan (list a b) (list (list a b)))
          (check (not ok) "same-batch dependency is rejected")
          (check (eq :dependency-not-ready (getf (first reasons) :kind))
                 "same-batch dependency rejection is classified")))
      (let ((a (make-work-item :name :a :writes '(:x)))
            (b (make-work-item :name :b :reads '(:x))))
        (multiple-value-bind (ok reasons)
            (verify-parallel-plan (list a b) (list (list a b)))
          (check (not ok) "same-batch conflict is rejected")
          (check (eq :same-batch-conflict (getf (first reasons) :kind))
                 "same-batch conflict rejection is classified")))
      (let ((a (make-work-item :name :a))
            (b (make-work-item :name :b)))
        (multiple-value-bind (ok reasons)
            (verify-parallel-plan (list a b) (list (list a)))
          (check (not ok) "unscheduled task is rejected")
          (check (eq :unscheduled-task (getf (first reasons) :kind))
                 "unscheduled task rejection is classified")))
      (let* ((a (make-work-item :name :a :cost 10d0))
             (b (make-work-item :name :b :cost 8d0))
             (plan (plan-work-schedule (list a b)
                                       :spawn-overhead 1d0
                                       :min-speedup 1.1d0)))
        (check (parallel-plan-profitable-p plan)
               "large independent tasks are profitable to parallelize")
        (check (> (parallel-plan-speedup plan) 1.1d0)
               "plan exposes estimated speedup")
        (check (equal '((:a :b)) (getf (explain-parallel-plan plan) :batches))
               "explanation exposes batch names"))
      (let* ((parse (make-work-item :name :parse :cost 1d0))
             (infer (make-work-item :name :infer :depends-on '(:parse) :cost 3d0))
             (emit (make-work-item :name :emit :depends-on '(:parse) :cost 4d0))
             (test (make-work-item :name :test :depends-on '(:infer :emit) :cost 2d0))
             (analysis (analyze-work-dag (list parse infer emit test)))
             (slack (work-dag-analysis-task-slack analysis))
             (infer-slack (find :infer slack :key (lambda (row) (getf row :task)))))
        (check (work-dag-analysis-p analysis)
               "analyze-work-dag returns a work-dag-analysis")
        (check (= 10d0 (work-dag-analysis-total-cost analysis))
               "analysis records total work")
        (check (= 7d0 (work-dag-analysis-critical-path-cost analysis))
               "analysis finds dependency critical path")
        (check (equal '(1 2 1) (work-dag-analysis-frontier-widths analysis))
               "analysis records conflict-aware frontier widths")
        (check (= 2 (work-dag-analysis-max-frontier-width analysis))
               "analysis records max frontier width")
        (check (= 1d0 (getf infer-slack :slack))
               "analysis computes non-critical task slack"))
      (let* ((read-a (make-work-item :name :read-a :cost 1d0))
             (read-b (make-work-item :name :read-b :cost 1d0))
             (left (make-work-item :name :left :depends-on '(:read-a) :cost 3d0))
             (right (make-work-item :name :right :depends-on '(:read-b) :cost 5d0))
             (join (make-work-item :name :join :depends-on '(:left :right) :cost 2d0))
             (side (make-work-item :name :side :cost 100d0))
             (items (list read-a read-b left right join side))
             (left-cone (causal-cone items :left))
             (join-cone (causal-cone items :join))
             (join-metrics (work-cone-metrics join-cone)))
        (check (work-causal-cone-p left-cone)
               "causal-cone returns a work-causal-cone")
        (check (equal '(:left) (work-causal-cone-targets left-cone))
               "causal-cone records target names")
        (check (equal '(:read-a :left)
                      (mapcar #'work-item-name
                              (work-causal-cone-tasks left-cone)))
               "causal-cone keeps only transitive predecessors")
        (check (equal '(:left) (work-causal-cone-boundary left-cone))
               "causal-cone boundary records cone outputs")
        (check (equal '(:read-b :right :join :side)
                      (mapcar #'work-item-name
                              (work-causal-cone-excluded left-cone)))
               "causal-cone reports excluded out-of-cone work")
        (check (= 4d0 (work-causal-cone-total-cost left-cone))
               "causal-cone total cost excludes unrelated work")
        (check (= 4d0 (work-causal-cone-critical-path-cost left-cone))
               "causal-cone critical path is local to the cone")
        (check (equal '(2 2 1)
                      (work-causal-cone-frontier-widths join-cone))
               "join causal-cone preserves independent predecessor frontiers")
        (check (work-cone-metrics-p join-metrics)
               "work-cone-metrics returns a metrics object")
        (check (eq :causal (work-cone-metrics-kind join-metrics))
               "causal cone metrics record cone kind")
        (check (equal '(:join) (work-cone-metrics-roots join-metrics))
               "causal cone metrics record target roots")
        (check (= 5 (work-cone-metrics-task-count join-metrics))
               "causal cone metrics record task count")
        (check (= 1 (work-cone-metrics-exterior-count join-metrics))
               "causal cone metrics record excluded exterior count")
        (check (= 8d0 (work-cone-metrics-critical-path-cost join-metrics))
               "causal cone metrics record local critical path")
        (check (= 2 (work-cone-metrics-max-frontier-width join-metrics))
               "causal cone metrics record max frontier width")
        (check (< (abs (- (work-cone-metrics-serial-fraction join-metrics)
                          (/ 8d0 12d0)))
                  1d-12)
               "causal cone metrics expose serial fraction")
        (multiple-value-bind (plan cone)
            (causal-cone-plan items :join :max-workers 2)
          (check (eq :join (first (work-causal-cone-boundary cone)))
                 "causal-cone-plan returns the cone it planned")
          (check (= 5 (length (apply #'append
                                     (parallel-plan-batches plan))))
                 "causal-cone-plan excludes unrelated side work from plan")))
      (let* ((parse (make-work-item :name :parse :writes '(:ast) :cost 1d0))
             (infer (make-work-item :name :infer
                                    :reads '(:ast)
                                    :writes '(:types)
                                    :depends-on '(:parse)
                                    :cost 3d0))
             (emit (make-work-item :name :emit
                                   :reads '(:ast)
                                   :writes '(:cuda)
                                   :depends-on '(:parse)
                                   :cost 4d0))
             (test (make-work-item :name :test
                                   :reads '(:types :cuda)
                                   :depends-on '(:infer :emit)
                                   :cost 2d0))
             (side (make-work-item :name :side :cost 100d0))
             (items (list parse infer emit test side))
             (infer-cone (affected-cone items :infer))
             (resource-cone (affected-cone items :ast :change-kind :resource))
             (infer-metrics (work-cone-metrics infer-cone)))
        (check (work-affected-cone-p infer-cone)
               "affected-cone returns a work-affected-cone")
        (check (equal '(:infer)
                      (work-affected-cone-sources infer-cone))
               "affected-cone records source tasks")
        (check (equal '(:infer :test)
                      (mapcar #'work-item-name
                              (work-affected-cone-tasks infer-cone)))
               "affected-cone keeps downstream recomputation tasks")
        (check (equal '(:parse :emit)
                      (work-affected-cone-prerequisites infer-cone))
               "affected-cone records external prerequisites")
        (check (equal '(:test)
                      (work-affected-cone-boundary infer-cone))
               "affected-cone records forward cone boundary")
        (check (equal '(:parse :emit :side)
                      (mapcar #'work-item-name
                              (work-affected-cone-excluded infer-cone)))
               "affected-cone reports work outside the recomputation cone")
        (check (= 5d0 (work-affected-cone-total-cost infer-cone))
               "affected-cone total cost is local to recomputation")
        (check (eq :affected (work-cone-metrics-kind infer-metrics))
               "affected cone metrics record cone kind")
        (check (equal '(:infer) (work-cone-metrics-roots infer-metrics))
               "affected cone metrics record source roots")
        (check (= 2 (work-cone-metrics-task-count infer-metrics))
               "affected cone metrics record recomputation task count")
        (check (= 3 (work-cone-metrics-exterior-count infer-metrics))
               "affected cone metrics record excluded task count")
        (check (= 1d0 (work-cone-metrics-serial-fraction infer-metrics))
               "affected cone metrics expose fully serial recomputation")
        (check (equal '(:ast)
                      (work-affected-cone-resources resource-cone))
               "resource affected-cone records changed resources")
        (check (equal '(:parse :infer :emit :test)
                      (mapcar #'work-item-name
                              (work-affected-cone-tasks resource-cone)))
               "resource affected-cone starts from readers and writers")
        (multiple-value-bind (plan cone)
            (affected-cone-plan items :infer :max-workers 2)
          (check (equal '(:test) (work-affected-cone-boundary cone))
                 "affected-cone-plan returns the cone it planned")
          (check (= 2 (length (apply #'append
                                     (parallel-plan-batches plan))))
                 "affected-cone-plan schedules only recomputation tasks")))
      (let* ((parse (make-work-item :name :parse
                                    :writes '(:ast)
                                    :cost 1d0))
             (infer (make-work-item :name :infer
                                    :reads '(:ast)
                                    :writes '(:types)
                                    :depends-on '(:parse)
                                    :cost 3d0))
             (emit (make-work-item :name :emit
                                   :reads '(:ast)
                                   :writes '(:cuda)
                                   :depends-on '(:parse)
                                   :cost 4d0))
             (test (make-work-item :name :test
                                   :reads '(:types :cuda)
                                   :depends-on '(:infer :emit)
                                   :cost 2d0))
             (score (score-work-action
                     (list parse infer emit test)
                     :compute-weight 1d0
                     :critical-path-weight 2d0
                     :communication-weight 0.5d0
                     :parallelism-pressure-weight 0.25d0)))
        (check (work-action-score-p score)
               "score-work-action returns a work-action-score")
        (check (= 10d0 (work-action-score-compute-cost score))
               "action score records compute cost")
        (check (= 7d0 (work-action-score-critical-path-cost score))
               "action score records critical path cost")
        (check (= 7d0 (work-action-score-communication-cost score))
               "action score records communication footprint")
        (check (= 1d0 (work-action-score-parallelism-pressure score))
               "action score records excess frontier width")
        (check (= 27.75d0 (work-action-score-value score))
               "action score combines weighted terms deterministically")
        (check (equal '(:compute 1.0d0
                       :critical-path 2.0d0
                       :communication 0.5d0
                       :parallelism-pressure 0.25d0)
                      (work-action-score-weights score))
               "action score records weights"))
      (let* ((read-a (make-work-item :name :read-a :cost 1d0))
             (read-b (make-work-item :name :read-b :cost 1d0))
             (left (make-work-item :name :left
                                   :depends-on '(:read-a)
                                   :cost 3d0))
             (right (make-work-item :name :right
                                    :depends-on '(:read-b)
                                    :cost 5d0))
             (join (make-work-item :name :join
                                   :depends-on '(:left :right)
                                   :cost 2d0))
             (side (make-work-item :name :side :cost 100d0))
             (items (list read-a read-b left right join side)))
        (multiple-value-bind (score cone)
            (score-causal-cone-action items :left
                                      :communication-weight 0d0
                                      :parallelism-pressure-weight 0d0)
          (check (equal '(:read-a :left)
                        (mapcar #'work-item-name
                                (work-causal-cone-tasks cone)))
                 "score-causal-cone-action scores only causal tasks")
          (check (= 8d0 (work-action-score-value score))
                 "causal cone action score excludes unrelated side work")))
      (let* ((fast-a (make-work-item :name :fast-a :cost 1d0))
             (fast-b (make-work-item :name :fast-b :cost 1d0))
             (slow-a (make-work-item :name :slow-a :cost 1d0))
             (slow-b (make-work-item :name :slow-b
                                     :depends-on '(:slow-a)
                                     :cost 3d0))
             (slow-c (make-work-item :name :slow-c
                                     :depends-on '(:slow-b)
                                     :cost 5d0))
             (ranked (rank-work-actions
                      (list (list :name :serial
                                  :items (list slow-a slow-b slow-c))
                            (list :name :parallel
                                  :items (list fast-a fast-b)))
                      :communication-weight 0d0
                      :parallelism-pressure-weight 0d0))
             (best (minimize-work-action
                    (list (list :name :serial
                                :items (list slow-a slow-b slow-c))
                          (list :name :parallel
                                :items (list fast-a fast-b)))
                    :communication-weight 0d0
                    :parallelism-pressure-weight 0d0)))
        (check (every #'work-action-choice-p ranked)
               "rank-work-actions returns work-action-choice objects")
        (check (equal '(:parallel :serial)
                      (mapcar #'work-action-choice-name ranked))
               "rank-work-actions sorts candidates by lower action")
        (check (eq :parallel (work-action-choice-name best))
               "minimize-work-action returns the lowest-action candidate")
        (check (< (work-action-score-value
                   (work-action-choice-score (first ranked)))
                  (work-action-score-value
                   (work-action-choice-score (second ranked))))
               "ranked action choices expose sorted score values"))
      (let* ((fast-a (make-work-item :name :fast-a :cost 1d0))
             (fast-b (make-work-item :name :fast-b :cost 1d0))
             (slow-a (make-work-item :name :slow-a :cost 1d0))
             (slow-b (make-work-item :name :slow-b
                                     :depends-on '(:slow-a)
                                     :cost 3d0))
             (slow-c (make-work-item :name :slow-c
                                     :depends-on '(:slow-b)
                                     :cost 5d0))
             (ensemble (work-action-ensemble
                        (list (list :name :serial
                                    :items (list slow-a slow-b slow-c))
                              (list :name :parallel
                                    :items (list fast-a fast-b)))
                        :temperature 0.25d0
                        :communication-weight 0d0
                        :parallelism-pressure-weight 0d0))
             (probabilities (work-action-ensemble-probabilities ensemble))
             (parallel-row (find :parallel probabilities
                                 :key (lambda (row) (getf row :name))))
             (total-probability (reduce #'+ probabilities
                                        :key (lambda (row)
                                               (getf row :probability)))))
        (check (work-action-ensemble-p ensemble)
               "work-action-ensemble returns an ensemble object")
        (check (eq :parallel
                   (work-action-choice-name
                    (work-action-ensemble-winner ensemble)))
               "work-action-ensemble winner is the minimum-action choice")
        (check (< (abs (- 1d0 total-probability)) 1d-12)
               "work-action-ensemble probabilities normalize")
        (check (> (getf parallel-row :probability) 0.99d0)
               "low-temperature ensemble concentrates on the minimum action")
        (check (<= (work-action-ensemble-free-energy ensemble)
                   (work-action-score-value
                    (work-action-choice-score
                     (work-action-ensemble-winner ensemble))))
               "finite-temperature free energy does not exceed the minimum energy"))
      (let* ((read-a (make-work-item :name :read-a :cost 1d0))
             (read-b (make-work-item :name :read-b :cost 1d0))
             (left (make-work-item :name :left
                                   :depends-on '(:read-a)
                                   :cost 3d0))
             (right (make-work-item :name :right
                                    :depends-on '(:read-b)
                                    :cost 5d0))
             (join (make-work-item :name :join
                                   :depends-on '(:left :right)
                                   :cost 2d0))
             (items (list read-a read-b left right join))
             (ranked (rank-causal-cone-actions
                      items
                      '(:join :left)
                      :communication-weight 0d0
                      :parallelism-pressure-weight 0d0))
             (best (minimize-causal-cone-action
                    items
                    '(:join :left)
                    :communication-weight 0d0
                    :parallelism-pressure-weight 0d0)))
        (check (equal '(:left :join)
                      (mapcar #'work-action-choice-name ranked))
               "rank-causal-cone-actions sorts target cones by lower action")
        (check (eq :left (work-action-choice-name best))
               "minimize-causal-cone-action returns the cheapest target")
        (check (equal '(:read-a :left)
                      (mapcar #'work-item-name
                              (work-action-choice-items best)))
               "causal action choice stores only cone tasks")
        (check (equal '(:join)
                      (work-causal-cone-targets
                       (work-action-choice-cone (second ranked))))
               "causal action choice retains the cone certificate"))
      (let* ((read-a (make-work-item :name :read-a :cost 1d0))
             (read-b (make-work-item :name :read-b :cost 1d0))
             (left (make-work-item :name :left
                                   :depends-on '(:read-a)
                                   :cost 3d0))
             (right (make-work-item :name :right
                                    :depends-on '(:read-b)
                                    :cost 5d0))
             (join (make-work-item :name :join
                                   :depends-on '(:left :right)
                                   :cost 2d0))
             (items (list read-a read-b left right join))
             (ensemble (causal-cone-action-ensemble
                        items '(:join :left)
                        :temperature 1d0
                        :communication-weight 0d0
                        :parallelism-pressure-weight 0d0)))
        (check (eq :left
                   (work-action-choice-name
                    (work-action-ensemble-winner ensemble)))
               "causal-cone-action-ensemble ranks cheapest target cone first")
        (check (= 2 (length (work-action-ensemble-probabilities ensemble)))
               "causal-cone-action-ensemble exposes one probability per target")
        (check (work-action-choice-cone
                (work-action-ensemble-winner ensemble))
               "causal-cone-action-ensemble retains cone metadata"))
      (let* ((fast-a (make-work-item :name :fast-a :cost 1d0))
             (fast-b (make-work-item :name :fast-b :cost 1d0))
             (slow-a (make-work-item :name :slow-a :cost 1d0))
             (slow-b (make-work-item :name :slow-b
                                     :depends-on '(:slow-a)
                                     :cost 3d0))
             (candidates (list (list :name :serial
                                     :items (list slow-a slow-b))
                               (list :name :parallel
                                     :items (list fast-a fast-b))))
             (certificate (action-choice-certificate
                           candidates
                           :communication-weight 0d0
                           :parallelism-pressure-weight 0d0))
             (payload (rosette-proof-witness:certificate-payload certificate)))
        (check (rosette-proof-witness:certificate-p certificate)
               "action-choice-certificate returns a proof-witness certificate")
        (check (eq :parallel (getf payload :winner))
               "action-choice-certificate records the minimum-action winner")
        (check (= 2 (length (getf payload :scores)))
               "action-choice-certificate records ranked score rows")
        (multiple-value-bind (ok reasons)
            (verify-action-choice-certificate candidates certificate)
          (check ok "action-choice certificate independently verifies")
          (check (null reasons) "valid action-choice certificate has no reasons"))
        (let* ((slow-b-mutated (make-work-item :name :slow-b
                                               :depends-on '(:slow-a)
                                               :cost 30d0))
               (mutated (list (list :name :serial
                                    :items (list slow-a slow-b-mutated))
                              (list :name :parallel
                                    :items (list fast-a fast-b)))))
          (multiple-value-bind (ok reasons)
              (verify-action-choice-certificate mutated certificate)
            (check (not ok)
                   "action-choice certificate detects changed descriptors")
            (check (eq :candidate-signature-mismatch
                       (getf (first reasons) :kind))
                   "changed action-choice descriptor rejection is classified"))))
      (let* ((fast-a (make-work-item :name :fast-a :cost 1d0))
             (fast-b (make-work-item :name :fast-b :cost 1d0))
             (slow-a (make-work-item :name :slow-a :cost 1d0))
             (slow-b (make-work-item :name :slow-b
                                     :depends-on '(:slow-a)
                                     :cost 3d0))
             (candidates (list (list :name :serial
                                     :items (list slow-a slow-b))
                               (list :name :parallel
                                     :items (list fast-a fast-b))))
             (certificate (action-ensemble-certificate
                           candidates
                           :temperature 0.5d0
                           :communication-weight 0d0
                           :parallelism-pressure-weight 0d0))
             (payload (rosette-proof-witness:certificate-payload certificate)))
        (check (rosette-proof-witness:certificate-p certificate)
               "action-ensemble-certificate returns a proof-witness certificate")
        (check (eq :parallel (getf payload :winner))
               "action-ensemble-certificate records the most probable winner")
        (check (= 2 (length (getf payload :probabilities)))
               "action-ensemble-certificate records probability rows")
        (multiple-value-bind (ok reasons)
            (verify-action-ensemble-certificate candidates certificate)
          (check ok "action-ensemble certificate independently verifies")
          (check (null reasons)
                 "valid action-ensemble certificate has no reasons"))
        (let* ((tampered-payload (copy-list payload))
               (tampered (rosette-proof-witness:make-certificate
                          :name :tampered-work-action-ensemble
                          :kind :work-action-ensemble
                          :claim :finite-temperature-action-ensemble
                          :payload tampered-payload
                          :passed t)))
          (setf (getf tampered-payload :free-energy) 999d0)
          (multiple-value-bind (ok reasons)
              (verify-action-ensemble-certificate candidates tampered)
            (check (not ok)
                   "action-ensemble certificate detects tampered thermodynamics")
            (check (eq :free-energy (getf (first reasons) :field))
                   "tampered action-ensemble rejection names the changed field")))
        (let* ((slow-b-mutated (make-work-item :name :slow-b
                                               :depends-on '(:slow-a)
                                               :cost 30d0))
               (mutated (list (list :name :serial
                                    :items (list slow-a slow-b-mutated))
                              (list :name :parallel
                                    :items (list fast-a fast-b)))))
          (multiple-value-bind (ok reasons)
              (verify-action-ensemble-certificate mutated certificate)
            (check (not ok)
                   "action-ensemble certificate detects changed descriptors")
            (check (eq :candidate-signature-mismatch
                       (getf (first reasons) :kind))
                   "changed ensemble descriptor rejection is classified"))))
      (let* ((laws (list :h (list :commutative t :idempotent t)
                         :n (list :nilpotent 2)))
             (left (make-work-item :name :left
                                   :writes '(:shared)
                                   :metadata '(:effect-word (:h :h))))
             (right (make-work-item :name :right
                                    :writes '(:shared)
                                    :metadata '(:effect-word (:h))))
             (blocked (make-work-item :name :blocked
                                      :writes '(:shared)
                                      :metadata '(:effect-word (:n))))
             (normalized (normalize-work-item-effects left laws))
             (items (apply-algebraic-commutes (list left right blocked) laws))
             (left* (find :left items :key #'work-item-name))
             (right* (find :right items :key #'work-item-name))
             (blocked* (find :blocked items :key #'work-item-name)))
        (check (equal '(:h)
                      (getf (work-item-metadata normalized)
                            :effect-normal-form))
               "normalize-work-item-effects stores algebraic normal form")
        (check (algebraic-commute-p left right laws)
               "algebraic-commute-p proves equal idempotent effects commute")
        (check (not (algebraic-commute-p left blocked laws))
               "algebraic-commute-p remains conservative for nonmatching effects")
        (check (member :right (work-item-commutes-with left*) :test #'equal)
               "apply-algebraic-commutes records inferred commute on left")
        (check (member :left (work-item-commutes-with right*) :test #'equal)
               "apply-algebraic-commutes records inferred commute on right")
        (check (not (member :left
                            (work-item-commutes-with blocked*)
                            :test #'equal))
               "apply-algebraic-commutes does not certify noncommuting task")
        (check (equal '((:left :right) (:blocked))
                      (batch-names (parallel-batches items)))
               "algebraic commute certificates unlock safe same-frontier work"))
      (let* ((parse (make-work-item :name :parse :cost 1d0))
             (infer (make-work-item :name :infer :depends-on '(:parse) :cost 3d0))
             (emit (make-work-item :name :emit :depends-on '(:parse) :cost 4d0))
             (test (make-work-item :name :test :depends-on '(:infer :emit) :cost 2d0))
             (bottlenecks (schedule-bottlenecks (list parse infer emit test)))
             (top (first bottlenecks))
             (infer-row (find :infer bottlenecks
                              :key (lambda (row) (getf row :task)))))
        (check (eq :parse (getf top :task))
               "schedule-bottlenecks ranks shared critical predecessors first")
        (check (getf top :critical-p)
               "top bottleneck is on a critical path")
        (check (= 9d0 (getf top :downstream-cost))
               "bottlenecks include downstream cost")
        (check (not (getf infer-row :critical-p))
               "bottlenecks expose non-critical slack")
        (check (equal '(:parse :emit)
                      (mapcar (lambda (row) (getf row :task))
                              (schedule-bottlenecks (list parse infer emit test)
                                                    :max-count 2)))
               "schedule-bottlenecks respects max-count"))
      (let* ((parse (make-work-item :name :parse :cost 1d0))
             (infer (make-work-item :name :infer :depends-on '(:parse) :cost 3d0))
             (emit (make-work-item :name :emit :depends-on '(:parse) :cost 4d0))
             (test (make-work-item :name :test :depends-on '(:infer :emit) :cost 2d0))
             (hints (schedule-optimization-hints (list parse infer emit test)))
             (first-hint (first hints))
             (infer-hint (find :infer hints
                               :key (lambda (row) (getf row :task)))))
        (check (eq :split-shared-predecessor (getf first-hint :action))
               "critical fanout receives split-shared-predecessor hint")
        (check (eq :critical-fanout (getf first-hint :reason))
               "optimization hint records reason")
        (check (eq :defer-or-batch-slack-work (getf infer-hint :action))
               "positive slack receives defer-or-batch hint"))
      (let* ((a (make-work-item :name :a :writes '(:a) :cost 2d0))
             (b (make-work-item :name :b :depends-on '(:a) :writes '(:b) :cost 2d0))
             (plan (plan-work-schedule (list a b)))
             (certificate (schedule-certificate (list a b) plan))
             (payload (rosette-proof-witness:certificate-payload certificate)))
        (check (rosette-proof-witness:certificate-p certificate)
               "schedule-certificate returns a proof-witness certificate")
        (check (rosette-proof-witness:runtime-verify certificate)
               "schedule certificate has a runtime-verifiable passed bit")
        (check (eq :a (getf (first (getf payload :bottlenecks)) :task))
               "schedule certificate records bottleneck summary")
        (multiple-value-bind (ok reasons)
            (verify-schedule-certificate (list a b) certificate)
          (check ok "schedule certificate independently verifies")
          (check (null reasons) "valid schedule certificate has no reasons")))
      (let* ((a (make-work-item :name :a :writes '(:a) :cost 2d0))
             (b (make-work-item :name :b :depends-on '(:a) :writes '(:b) :cost 2d0))
             (bad (schedule-certificate (list a b) (list (list a b)))))
        (check (not (rosette-proof-witness:certificate-passed bad))
               "invalid schedule certificate records failed verification")
        (multiple-value-bind (ok reasons)
            (verify-schedule-certificate (list a b) bad)
          (check (not ok) "invalid schedule certificate re-verifies as invalid")
          (check (eq :dependency-not-ready (getf (first reasons) :kind))
                 "invalid schedule certificate preserves verifier classification")))
      (let* ((a (make-work-item :name :a :cost 2d0))
             (b (make-work-item :name :b :cost 2d0))
             (plan (plan-work-schedule (list a b)))
             (certificate (schedule-certificate (list a b) plan))
             (b-mutated (make-work-item :name :b :cost 3d0)))
        (multiple-value-bind (ok reasons)
            (verify-schedule-certificate (list a b-mutated) certificate)
          (check (not ok) "schedule certificate detects changed work descriptors")
          (check (eq :item-signature-mismatch (getf (first reasons) :kind))
                 "changed descriptor rejection is classified")))
      (let* ((a (make-work-item :name :a :cost 1d0))
             (b (make-work-item :name :b :cost 1d0))
             (plan (plan-work-schedule (list a b)
                                       :spawn-overhead 10d0
                                       :min-speedup 1.1d0)))
        (check (not (parallel-plan-profitable-p plan))
               "overhead can make safe parallelism not worth taking"))
      (let* ((a (make-work-item :name :a :cost 5d0))
             (b (make-work-item :name :b :cost 4d0))
             (c (make-work-item :name :c :cost 3d0))
             (unbounded (plan-work-schedule (list a b c)))
             (bounded (plan-work-schedule (list a b c) :max-workers 2)))
        (check (= 5d0 (parallel-plan-parallel-cost unbounded))
               "unbounded frontier cost is the max task cost")
        (check (= 7d0 (parallel-plan-parallel-cost bounded))
               "bounded frontier cost accounts for worker waves")
        (check (= 2 (getf (parallel-plan-reasons bounded) :max-workers))
               "bounded worker count is recorded in plan reasons"))
      (let* ((a (make-work-item :name :a :cost 5d0))
             (b (make-work-item :name :b :cost 4d0))
             (c (make-work-item :name :c :cost 3d0))
             (lanes (worker-lanes (list a b c) :max-workers 2))
             (lane-names (mapcar (lambda (frontier)
                                   (mapcar (lambda (lane)
                                             (mapcar #'work-item-name lane))
                                           frontier))
                                 lanes)))
        (check (equal '(((:a) (:b :c))) lane-names)
               "worker-lanes exposes bounded-worker assignments"))
      (let ((laws (list :project (list :idempotent t)
                        :observe (list :projector t)
                        :erase (list :nilpotent 3)
                        :flip (list :involutive t)
                        :shear (list :unipotent 3)
                        :a (list :commutative t)
                        :b (list :commutative t)
                        :unit (list :identity t)
                        :zero (list :absorbing t)
                        :create (list :annihilates '(:destroy))
                        :destroy (list :annihilates '(:create))
                        :x (list :anticommutes-with '(:y))
                        :y (list :anticommutes-with '(:x))
                        :flow (list :monotone t))))
        (multiple-value-bind (normal trace)
            (normalize-effect-word
             '(:project :project
               :erase :erase :erase
               :flip :flip :flip
               :shear :shear :shear :shear
               :b :a
               :flow
               :b :a)
             laws)
          (check (equal '(:project
                          :flip
                          (:unipotent :shear 1)
                          :a :b
                          :flow
                          :a :b)
                        normal)
                 "normalize-effect-word applies idempotent nilpotent involutive unipotent commutative and monotone laws")
          (check (find :monotone trace :key (lambda (row) (getf row :law)))
                 "normalize-effect-word records monotone barriers")
          (check (= 2 (count :commutative trace
                             :key (lambda (row) (getf row :law))))
                 "normalize-effect-word records both commutative regions"))
        (multiple-value-bind (normal trace phase)
            (normalize-effect-word '(:unit :project :unit) laws)
          (check (equal '(:project) normal)
                 "normalize-effect-word removes identity effects")
          (check (= 2 (count :identity trace
                             :key (lambda (row) (getf row :law))))
                 "normalize-effect-word records identity removals")
          (check (= 1 phase)
                 "identity normalization preserves phase"))
        (multiple-value-bind (normal trace phase)
            (normalize-effect-word '(:project :zero :flip) laws)
          (check (equal '(:zero) normal)
                 "normalize-effect-word collapses absorbing effects")
          (check (eq :absorbing (getf (first trace) :law))
                 "normalize-effect-word records absorbing collapse")
          (check (= 1 phase)
                 "absorbing normalization preserves scalar phase"))
        (multiple-value-bind (normal trace phase)
            (normalize-effect-word '(:y :x) laws)
          (check (equal '(:x :y) normal)
                 "normalize-effect-word canonicalizes anticommuting effects")
          (check (= -1 phase)
                 "normalize-effect-word tracks anticommuting swap phase")
          (check (find :anticommutative trace
                       :key (lambda (row) (getf row :law)))
                 "normalize-effect-word records anticommuting rewrites"))
        (multiple-value-bind (normal trace phase)
            (normalize-effect-word
             '(:observe :observe :create :destroy :flip)
             laws)
          (check (equal '(:observe :flip) normal)
                 "normalize-effect-word applies projector and annihilation laws")
          (check (find :projector trace :key (lambda (row) (getf row :law)))
                 "normalize-effect-word records projector collapse")
          (check (find :annihilation trace :key (lambda (row) (getf row :law)))
                 "normalize-effect-word records annihilating pair removal")
          (check (= 1 phase)
                 "projector and annihilation normalization preserves phase"))
        (let* ((certificate
                 (effect-word-certificate
                  '(:project :project :flip :flip :flip)
                  laws))
               (payload (rosette-proof-witness:certificate-payload certificate)))
          (multiple-value-bind (ok reasons)
              (verify-effect-word-certificate certificate)
            (check ok "effect-word certificate independently verifies")
            (check (null reasons)
                   "valid effect-word certificate has no reasons"))
          (let* ((tampered-payload (copy-list payload))
                 (tampered (rosette-proof-witness:make-certificate
                            :name :tampered-effect-word
                            :kind :effect-word-normalization
                            :claim :algebraic-effect-normal-form
                            :payload tampered-payload
                            :passed t)))
            (setf (getf tampered-payload :normal-form) '(:wrong))
            (multiple-value-bind (ok reasons)
                (verify-effect-word-certificate tampered)
              (check (not ok)
                     "effect-word certificate detects tampered normal form")
              (check (eq :effect-normal-form-mismatch
                         (getf (first reasons) :kind))
                     "tampered effect-word rejection is classified")))))
      (handler-case
          (progn
            (plan-work-schedule (list (make-work-item :name :a)) :max-workers 0)
            (check nil "invalid max-workers should signal"))
        (error ()
          (check t "invalid max-workers signals")))
      (handler-case
          (progn
            (work-action-ensemble
             (list (list :name :a
                         :items (list (make-work-item :name :a))))
             :temperature 0d0)
            (check nil "invalid ensemble temperature should signal"))
        (error ()
          (check t "invalid ensemble temperature signals"))))
    (format t "rosette-work-scheduler: ~D assertions, 0 failures~%" assertions)
    assertions))
