;;;; tests.lisp --- tests for rosette-probability-core.

(defpackage #:rosette-probability-core/tests
  (:use #:cl #:rosette-probability-core)
  (:import-from #:rosette-scalar-core
                #:approx=))

(in-package #:rosette-probability-core/tests)

(defun near= (a b &optional (eps 1d-9))
  (approx= a b eps))

(defmacro is (condition message)
  `(unless ,condition
     (error "FAIL: ~A" ,message)))

(defmacro signals-error (&body body)
  `(handler-case
       (progn ,@body nil)
     (error () t)))

(defun run-all-tests ()
  (let ((assertions 0))
    (flet ((ok (condition message)
             (incf assertions)
             (is condition message)))
      (ok (near= (normal-pdf 0d0) (/ 1d0 (sqrt (* 2d0 pi))) 1d-15)
          "normal-pdf matches density at zero")
      (ok (near= (normal-pdf -2d0) (normal-pdf 2d0) 1d-15)
          "normal-pdf is even")
      (ok (> (normal-pdf 0d0) (normal-pdf 1d0) (normal-pdf 2d0))
          "normal-pdf decreases away from zero on the positive axis")
      (ok (near= (normal-cdf 0d0) 0.5d0 1d-7)
          "normal-cdf is centered")
      (ok (near= (normal-cdf (- 1d0)) (- 1d0 (normal-cdf 1d0)) 1d-12)
          "normal-cdf symmetry")
      (ok (< (normal-cdf -2d0) (normal-cdf 0d0) (normal-cdf 2d0))
          "normal-cdf is monotone increasing")
      (ok (near= (inverse-normal-cdf 0.5d0) 0d0 1d-12)
          "inverse-normal-cdf is centered")
      (ok (near= (inverse-normal-cdf 0.975d0) 1.959963986d0 1d-6)
          "inverse-normal-cdf matches the standard 97.5% quantile")
      (ok (near= (normal-cdf (inverse-normal-cdf 0.84d0)) 0.84d0 1d-5)
          "inverse-normal-cdf round-trips through normal-cdf")
      (ok (signals-error (inverse-normal-cdf 0d0))
          "inverse-normal-cdf rejects p=0")
      (ok (signals-error (inverse-normal-cdf 1d0))
          "inverse-normal-cdf rejects p=1")
      (ok (near= (black-scholes-d1-drift-term 0.05d0 0.02d0 0.2d0 2d0)
                 0.1d0
                 1d-15)
          "black-scholes-d1-drift-term computes (r-q+sigma^2/2)T")
      (ok (near= (black-scholes-d1-drift-term 0d0 0d0 0d0 3d0)
                 0d0
                 1d-15)
          "black-scholes-d1-drift-term is zero for zero rate/dividend/volatility")
      (let ((q (inverse-gaussian-quantile 0.5d0 1d0 1d0)))
        (ok (near= (inverse-gaussian-cdf q 1d0 1d0) 0.5d0 1d-9)
            "inverse-gaussian-quantile inverts CDF"))
      (ok (plusp (inverse-gaussian-pdf 1d0 1d0 1d0))
          "inverse-gaussian-pdf is positive in-domain")
      (ok (> (inverse-gaussian-cdf 2d0 1d0 1d0)
             (inverse-gaussian-cdf 1d0 1d0 1d0)
             (inverse-gaussian-cdf 0.5d0 1d0 1d0))
          "inverse-gaussian-cdf is monotone increasing in x")
      (ok (near= (inverse-gaussian-cdf 1d-9 1d0 1d0) 0d0 1d-6)
          "inverse-gaussian-cdf approaches zero near the positive boundary")
      (let ((q25 (inverse-gaussian-quantile 0.25d0 1.5d0 2d0))
            (q75 (inverse-gaussian-quantile 0.75d0 1.5d0 2d0)))
        (ok (< q25 q75)
            "inverse-gaussian-quantile is monotone in probability")
        (ok (near= (inverse-gaussian-cdf q25 1.5d0 2d0) 0.25d0 1d-8)
            "inverse-gaussian-quantile round-trips p=0.25")
        (ok (near= (inverse-gaussian-cdf q75 1.5d0 2d0) 0.75d0 1d-8)
            "inverse-gaussian-quantile round-trips p=0.75"))
      (ok (signals-error (inverse-gaussian-pdf 0d0 1d0 1d0))
          "inverse-gaussian-pdf rejects nonpositive x")
      (ok (signals-error (inverse-gaussian-cdf 1d0 0d0 1d0))
          "inverse-gaussian-cdf rejects nonpositive mu")
      (ok (signals-error (inverse-gaussian-quantile 0.5d0 1d0 0d0))
          "inverse-gaussian-quantile rejects nonpositive lambda")
      (ok (signals-error (inverse-gaussian-quantile 1d0 1d0 1d0))
          "inverse-gaussian-quantile rejects p=1"))
    (format t "rosette-probability-core: ~D assertions, 0 failures~%" assertions)
    assertions))
