;;;; face-lattice.lisp --- the cube, increment 5: the face lattice, systems of
;;;; partial elements, and a comp that SOLVES over a cofibration.
;;;;
;;;; Increments 0-4 modelled hcomp/comp by folding a tube in value space -- an
;;;; honest stand-in, but NOT the real cubical primitive.  Genuine cubical Kan
;;;; composition is indexed by a COFIBRATION: a face formula phi in the FACE
;;;; LATTICE (the De Morgan algebra generated by the atomic constraints
;;;; (i = 0), (i = 1), closed under /\ and \/, with top 1F and bottom 0F).  A
;;;; partial element is a SYSTEM  [phi_1 -> u_1, ...]  -- a value defined only
;;;; where its faces hold, required to AGREE on overlaps (compatibility).  comp
;;;; transports a cap along a type-line while AGREEING with such a system on
;;;; the boundary; the cap must match the system at the i0 end (the adjacency
;;;; side-condition real cubical imposes and the value-fold could not state).
;;;;
;;;; THE WALL after this (the remaining climb to pi_4(S^3) = Z/2): connections
;;;; (/\, \/ past the endpoints) inside the Kan operation, comp for the Pi / Sigma
;;;; / Path type-formers, the Glue comp (not just transp), and the higher hcomp
;;;; that fills S^2.  This file builds the cofibration algebra those all need.

(in-package #:rosette-cubical-core)

;;; ---- The face lattice (cofibration algebra) --------------------------

(defun f-top () "The true cofibration 1F (always holds)." :top)
(defun f-bot () "The false cofibration 0F (never holds)." :bot)
(defun f-eq0 (dim) "The atomic face (DIM = 0)." (list :eq0 dim))
(defun f-eq1 (dim) "The atomic face (DIM = 1)." (list :eq1 dim))
(defun f-and (a b) "Meet of cofibrations  A /\\ B." (list :and a b))
(defun f-or (a b) "Join of cofibrations  A \\/ B." (list :or a b))

(defun face-p (phi)
  "Well-formedness of a face formula."
  (cond ((member phi '(:top :bot)) t)
        ((and (consp phi) (member (first phi) '(:eq0 :eq1))) t)
        ((and (consp phi) (member (first phi) '(:and :or)))
         (and (face-p (second phi)) (face-p (third phi))))
        (t nil)))

(defun eval-face (phi env)
  "Does cofibration PHI HOLD under ENV (an alist dim -> :0/:1)?  An atomic
(DIM = e) holds when ENV binds DIM to that endpoint.  /\\ is conjunction,
\\/ disjunction, with the lattice top/bottom."
  (cond ((eq phi :top) t)
        ((eq phi :bot) nil)
        ((eq (first phi) :eq0) (eq (cdr (assoc (second phi) env)) :0))
        ((eq (first phi) :eq1) (eq (cdr (assoc (second phi) env)) :1))
        ((eq (first phi) :and) (and (eval-face (second phi) env) (eval-face (third phi) env)))
        ((eq (first phi) :or) (or (eval-face (second phi) env) (eval-face (third phi) env)))
        (t (error "Not a face formula: ~S." phi))))

(defun face-contradictory-p (dim)
  "(DIM=0) /\\ (DIM=1) never holds -- the lattice meet of opposite endpoints
is 0F.  A small soundness witness for the algebra."
  (and (not (eval-face (f-and (f-eq0 dim) (f-eq1 dim)) (list (cons dim :0))))
       (not (eval-face (f-and (f-eq0 dim) (f-eq1 dim)) (list (cons dim :1))))))

;;; ---- Systems of partial elements -------------------------------------

(defstruct (system (:constructor %make-system (clauses)))
  "A partial element: a list of CLAUSES (phi . value), the value defined on
the cofibration phi.  Its domain is the join of the clause faces."
  (clauses nil :type list :read-only t))

(defun make-system (clauses)
  "Build a partial element from CLAUSES, a list of (face . value)."
  (dolist (c clauses)
    (unless (face-p (car c)) (error "System clause has a malformed face: ~S." (car c))))
  (%make-system clauses))

(defun system-domain-holds-p (sys env)
  "Does SYS's domain (the join of its clause faces) hold under ENV?"
  (some (lambda (c) (eval-face (car c) env)) (system-clauses sys)))

(defun system-value (sys env)
  "The value of SYS under ENV: the value of the FIRST clause whose face holds,
or NIL outside the domain."
  (dolist (c (system-clauses sys) nil)
    (when (eval-face (car c) env) (return (cdr c)))))

(defun system-compatible-p (sys envs &key (test #'eql))
  "Compatibility: wherever two clauses' faces BOTH hold (over the sample ENVS),
their values agree.  Real cubical requires this on the whole lattice; we check
it over a finite set of representative ENVS."
  (let ((clauses (system-clauses sys)))
    (dolist (env envs t)
      (let ((vals (loop for c in clauses
                        when (eval-face (car c) env) collect (cdr c))))
        (when (and (cdr vals)
                   (not (every (lambda (v) (funcall test v (first vals))) (rest vals))))
          (return nil))))))

;;; ---- comp over a cofibration -----------------------------------------

(defun comp-sys (line cap system &key (dim 'i) (test #'eql))
  "Genuine Kan composition along type-line LINE with composition dimension DIM:
transport CAP (the i0 face) along LINE, AGREEING with the partial element
SYSTEM on the boundary.  The cap-system adjacency side-condition is enforced:
where SYSTEM is defined at (DIM = 0) its value must equal CAP.  Returns the lid
(the i1 face): the system's value there if its (DIM=1) face holds, else the
transport of CAP.

Degeneracy: comp-sys with the EMPTY system = transp LINE CAP."
  (let ((env0 (list (cons dim :0)))
        (env1 (list (cons dim :1)))
        (src (type-line-at line :0)))
    (unless (in-type-p src cap)
      (error "comp-sys cap ~S not in (LINE i0) = ~S." cap (hott-type-name src)))
    ;; adjacency: the cap must match the system at the i0 end.
    (when (system-domain-holds-p system env0)
      (unless (funcall test (system-value system env0) cap)
        (error "comp-sys adjacency violated: system at (~a=0) = ~S /= cap ~S."
               dim (system-value system env0) cap)))
    ;; lid: read the system at i1 if defined there, else transport the cap.
    (if (system-domain-holds-p system env1)
        (system-value system env1)
        (transp line cap))))
