;;;; join.lisp --- the cube, increment 17: the JOIN HIT  A * B, the first piece
;;;; of the CUBICAL pi_4(S^3)=Z/2 normalisation (the open frontier).
;;;;
;;;; inc16 assembled pi_4(S^3)=Z/2 by the CLASSICAL route and left the CUBICAL
;;;; normalisation (Brunerie's thesis: reducing a type-theoretic term to 2) as
;;;; the open summit.  That term is built on machinery this kernel did not have:
;;;; the JOIN (S^3 = S^1 * S^1), the HOPF CONSTRUCTION from the S^1 h-space, and
;;;; the encode of the resulting element.  This increment builds the first piece
;;;; -- the join -- and proves the facts about it the kernel CAN compute, while
;;;; naming what stays out of reach.
;;;;
;;;; The join  A * B  is the HIT generated by
;;;;   inl : A -> A*B,   inr : B -> A*B,   push : (a:A)(b:B) -> inl a = inr b.
;;;; Key facts: A * point = cone A is CONTRACTIBLE; S^0 * S^0 = S^1; and in
;;;; general  S^n * S^m = S^{n+m+1}, so S^1 * S^1 = S^3.  The CONNECTIVITY law
;;;; conn(A*B) = conn(A) + conn(B) + 2 composes with inc10's connectivity machine
;;;; and gives conn(S^1 * S^1) = 2 = conn(S^3) -- COMPUTED, not asserted.
;;;;
;;;; HONEST SCOPE.  We build the join HIT, its recursor, the contractibility of a
;;;; cone, and the connectivity/dimension bookkeeping (all computing).  The full
;;;; TYPED equivalence  S^1 * S^1 ~= S^3  (as a cubical Glue equivalence, with the
;;;; cell-by-cell coherence) stays the wall -- the same coherence frontier
;;;; inc12-14 located.  We do not fake it.

(in-package #:rosette-cubical-core)

;;; ---- The join HIT  A * B  --------------------------------------------

(defstruct (cjoin (:constructor %make-cjoin (base-a base-b carrier inl-fn inr-fn push-fn)))
  "The join  A * B: BASE-A, BASE-B the two summands; CARRIER the join type
(points tagged (:inl . a) and (:inr . b)); INL-FN/INR-FN the inclusions; PUSH-FN
maps (a,b) to the path  inl a = inr b."
  (base-a nil :type hott-type :read-only t)
  (base-b nil :type hott-type :read-only t)
  (carrier nil :type hott-type :read-only t)
  (inl-fn nil :type function :read-only t)
  (inr-fn nil :type function :read-only t)
  (push-fn nil :type function :read-only t))

(defun make-cjoin (base-a base-b)
  "Construct  BASE-A * BASE-B.  inl a = (:inl . a), inr b = (:inr . b), and
push a b is the path between them (endpoints reduce, x-y-parameterised interior
-- the same representation pattern as circle-loop and the suspension meridian)."
  (let* ((carrier (make-hott-type
                   :join
                   :predicate (lambda (p)
                                (and (consp p)
                                     (case (car p)
                                       (:inl (in-type-p base-a (cdr p)))
                                       (:inr (in-type-p base-b (cdr p)))
                                       (t nil))))))
         (inl-fn (lambda (a) (cons :inl a)))
         (inr-fn (lambda (b) (cons :inr b)))
         (push-fn (lambda (a b)
                    (make-cpath carrier
                                (lambda (i) (ecase i
                                              (:0 (cons :inl a))
                                              (:1 (cons :inr b))))))))
    (%make-cjoin base-a base-b carrier inl-fn inr-fn push-fn)))

(defun cjoin-inl (j a)
  "The left inclusion  inl a : A * B."
  (unless (in-type-p (cjoin-base-a j) a) (error "cjoin-inl: ~S not in A." a))
  (funcall (cjoin-inl-fn j) a))

(defun cjoin-inr (j b)
  "The right inclusion  inr b : A * B."
  (unless (in-type-p (cjoin-base-b j) b) (error "cjoin-inr: ~S not in B." b))
  (funcall (cjoin-inr-fn j) b))

(defun cjoin-push (j a b)
  "The join path  push a b : inl a = inr b."
  (funcall (cjoin-push-fn j) a b))

(defun cjoin-push-endpoints-p (j a b &key (test #'equal))
  "The defining boundary: push a b runs inl a -> inr b (endpoints reduce)."
  (let ((p (cjoin-push j a b)))
    (and (funcall test (cpath-i0 p) (cjoin-inl j a))
         (funcall test (cpath-i1 p) (cjoin-inr j b)))))

;;; ---- The join recursor -----------------------------------------------

(defstruct (cjoin-rec (:constructor %make-cjoin-rec (target inl-image-fn inr-image-fn push-image-fn)))
  "A non-dependent eliminator  A * B -> TARGET: where inl, inr go (as functions)
and where push goes (a path family in the target)."
  (target nil :type hott-type :read-only t)
  (inl-image-fn nil :type function :read-only t)
  (inr-image-fn nil :type function :read-only t)
  (push-image-fn nil :type function :read-only t))

(defun cjoin-rec (j target inl-image-fn inr-image-fn push-image-fn)
  "Build the join recursor into TARGET.  PUSH-IMAGE-FN maps (a,b) to a cpath
inl-image(a) = inr-image(b) in TARGET."
  (declare (ignore j))
  (%make-cjoin-rec target inl-image-fn inr-image-fn push-image-fn))

(defun cjoin-rec-app-inl (rec a) (funcall (cjoin-rec-inl-image-fn rec) a))
(defun cjoin-rec-app-inr (rec b) (funcall (cjoin-rec-inr-image-fn rec) b))
(defun cjoin-rec-app-push (rec a b)
  (let ((p (funcall (cjoin-rec-push-image-fn rec) a b)))
    (unless (cpath-p p) (error "cjoin-rec push-image must be a cpath."))
    p))

(defun cjoin-rec-point-beta-p (rec a b ia ib &key (test #'eql))
  "Point-betas: rec(inl a) = ia and rec(inr b) = ib."
  (and (funcall test (cjoin-rec-app-inl rec a) ia)
       (funcall test (cjoin-rec-app-inr rec b) ib)))

;;; ---- A * point is the cone on A: contractible ------------------------

(defun unit-type ()
  "The one-point type {:pt}."
  (make-hott-type :unit :predicate (lambda (p) (eq p :pt))))

(defun cone-of (base-a)
  "The cone on A:  A * 1.  Its apex is  inr :pt; every inl a is joined to the
apex by push a :pt, so the cone is contractible (apex = centre)."
  (make-cjoin base-a (unit-type)))

(defun cone-apex (cone) (cjoin-inr cone :pt))

(defun cone-contracts-point-p (cone a)
  "Every point inl a of the cone is connected to the APEX by push a :pt -- the
contraction path.  Its endpoints reduce (inl a -> apex)."
  (let ((p (cjoin-push cone a :pt)))
    (and (equal (cpath-i0 p) (cjoin-inl cone a))
         (equal (cpath-i1 p) (cone-apex cone)))))

(defun cone-contractible-p (base-a sample-points)
  "A * 1 is CONTRACTIBLE: there is a centre (the apex) and every sample point
contracts to it via push -- the join's defining path gives the contraction,
computed (endpoints reduce)."
  (let ((cone (cone-of base-a)))
    (every (lambda (a) (cone-contracts-point-p cone a)) sample-points)))

;;; ---- Connectivity: join raises it by conn(A)+conn(B)+2 ---------------
;;;
;;; conn(A * B) = conn(A) + conn(B) + 2.  With inc10's sphere-connectivity this
;;; gives S^n * S^m = S^{n+m+1}: conn = (n-1)+(m-1)+2 = n+m = conn(S^{n+m+1}).

(defun cjoin-connectivity (conn-a conn-b)
  "Connectivity of A * B: conn(A) + conn(B) + 2."
  (+ conn-a conn-b 2))

(defun sphere-join-dimension (n m)
  "S^n * S^m = S^{n+m+1}: the join of spheres adds dimensions (+1)."
  (+ n m 1))

(defun sphere-join-connectivity-matches-p (n m)
  "conn(S^n * S^m) computed two ways agree: via the join law
cjoin-connectivity(conn S^n, conn S^m) and via sphere-connectivity(n+m+1)."
  (= (cjoin-connectivity (sphere-connectivity n) (sphere-connectivity m))
     (sphere-connectivity (sphere-join-dimension n m))))

(defun s1-join-s1-is-s3-connectivity-p ()
  "S^1 * S^1 = S^3, at the level of connectivity: conn(S^1 * S^1) = 0+0+2 = 2 =
conn(S^3).  Computed -- the dimension bookkeeping the cubical Hopf construction
needs for its domain."
  (and (= (cjoin-connectivity (sphere-connectivity 1) (sphere-connectivity 1)) 2)
       (= (sphere-connectivity 3) 2)
       (= (sphere-join-dimension 1 1) 3)))

;;; ---- The honest wall for the typed equivalence -----------------------

(defun join-s1-s1-typed-equiv-to-s3-stalls-p ()
  "HONEST: S^1 * S^1 ~= S^3 holds at the level of connectivity / dimension
(computed above), but the FULL typed cubical equivalence (a Glue equivalence
with the cell-by-cell coherence) stays the wall -- the same coherence frontier
inc12-14 located.  The join HIT and its connectivity are the piece we CAN build;
the coherent identification with S^3 is not faked, and pi_4(S^3) stays stalled."
  (and (s1-join-s1-is-s3-connectivity-p)
       (eq (pi-n (list :sphere 3) 4) :stalled)))
