;;;; pi4-encode.lisp --- the cube, increment 22: a COMPUTING encode at pi_4 --
;;;; the encode  pi_4(S^3) -> Z/2  as (Hopf invariant) mod 2, with computing values.
;;;;
;;;; The whole campaign produced encodes at pi_1 (winding -> Z, mod-k -> Z/k).  This
;;;; increment produces one at pi_4 -- the genuine object the cubical normalisation
;;;; aims at -- by COMPOSING pieces that already compute, and is scrupulous about
;;;; which step is computed and which is an encoded classical input.
;;;;
;;;; The structure (EHP): pi_4(S^3) = pi_3(S^2) / <Sigma's kernel>, and Freudenthal
;;;; (inc10) makes Sigma : pi_3(S^2) ->> pi_4(S^3) the edge SURJECTION; its kernel
;;;; is generated by the Whitehead square [iota_2,iota_2] = 2 eta (inc15).  So
;;;;   pi_4(S^3) = Z / 2Z = Z/2,
;;;; and the encode  pi_4(S^3) -> Z/2  is just  (Hopf invariant) mod 2.
;;;;
;;;; WHAT COMPUTES (genuinely, by ua-beta):
;;;;   * the Hopf invariant of n.eta in pi_3(S^2)=Z is n (inc18, H(eta)=1 via the
;;;;     bidegree);
;;;;   * mod 2 is the inc21 cyclic engine (order-2 monodromy).
;;;; So the encode VALUES compute:  eta_3 |-> 1,  2.eta_3 |-> 0,  n.eta_3 |-> n mod 2.
;;;;
;;;; WHAT IS ENCODED (a classical input, NOT normalised here):
;;;;   * that Sigma's kernel is EXACTLY <2 eta> (the EHP exactness) -- this is what
;;;;     makes the encode an ISO, i.e. pi_4(S^3) = Z/2 as a group.  The "2" in the
;;;;     kernel is inc15's cup square (computed); EHP exactness is the encoded
;;;;     theorem (same status as Freudenthal / the LES).
;;;;
;;;; SO: a computing encode at pi_4 (its values reduce), with the iso-property
;;;; resting on encoded EHP.  We do NOT flip the cubical table -- the FULL
;;;; normalisation (|| Omega^4 S^3 ||_0 reducing as a type) still needs the
;;;; higher-loop representability; pi-n (:sphere 3) 4 stays :stalled.

(in-package #:rosette-cubical-core)

;;; ---- The Hopf invariant on pi_3(S^2) = Z (computes) ------------------

(defun pi3-s2-hopf-invariant (n)
  "The Hopf invariant of  n . eta  in pi_3(S^2) = Z: since H(eta) = 1 (inc18, the
bidegree of the Hopf construction), H(n.eta) = n.  Computes."
  (* n (hopf-invariant-of-eta)))

;;; ---- The suspension kernel (EHP), with the 2 from inc15 --------------

(defun pi4-s3-suspension-kernel-generator ()
  "The kernel of the suspension Sigma : pi_3(S^2) -> pi_4(S^3) is generated by the
Whitehead square [iota_2,iota_2] = 2 eta -- so the generator's Hopf invariant is
2 (inc15's cup square).  (The fact that the kernel is EXACTLY this is EHP --
encoded; the 2 itself is computed.)"
  (classical-brunerie-number))                    ; = 2 (inc15, the cup square)

;;; ---- The encode  pi_4(S^3) -> Z/2  (computing values) ----------------
;;;
;;; pi_4(S^3) is generated by eta_3 = Sigma^2 eta (the image of eta).  Its general
;;; element is n . eta_3; the encode is the Hopf invariant n reduced mod the kernel
;;; generator's invariant (2) -- i.e. (Hopf invariant) mod 2, computed via the
;;; inc21 cyclic engine.

(defun pi4-s3-encode (n)
  "encode : pi_4(S^3) -> Z/2 on n . eta_3.  Compose the COMPUTING Hopf invariant
(n) with the COMPUTING mod-2 reduction (cyclic-encode, order-2 monodromy):
encode(n.eta_3) = n mod 2.  Values reduce by ua-beta."
  (cyclic-encode (pi4-s3-suspension-kernel-generator)    ; = 2
                 (pi3-s2-hopf-invariant n)))             ; = n, then mod 2

(defun pi4-s3-encode-eta3-is-1-p ()
  "encode(eta_3) = 1: the generator is non-trivial (H(eta)=1, odd)."
  (= (pi4-s3-encode 1) 1))

(defun pi4-s3-encode-2eta3-is-0-p ()
  "encode(2 . eta_3) = 0: twice the generator vanishes (H=2, even) -- the order-2
relation, computed."
  (= (pi4-s3-encode 2) 0))

(defun pi4-s3-encode-computes-p (&optional (range 8))
  "The encode pi_4(S^3) -> Z/2 has COMPUTING values across a range: encode(n.eta_3)
= n mod 2, via (Hopf invariant) then the order-2 cyclic reduction -- both ua-beta."
  (loop for n from (- range) to range
        always (= (pi4-s3-encode n) (mod n 2))))

;;; ---- The honest line: encode values compute, the iso/normalisation stalls ----

(defun pi4-s3-encode-iso-given-ehp-p ()
  "The encode pi_4(S^3) -> Z/2 is an ISOMORPHISM -- hence pi_4(S^3) = Z/2 -- GIVEN
that Sigma's kernel is exactly <2 eta> (EHP, encoded).  The encode VALUES compute
(eta_3 |-> 1, 2.eta_3 |-> 0); the kernel's 2 is inc15's cup square (computed);
the iso-property rests on the encoded EHP exactness.  We assert the structure, not
a normalisation."
  (and (pi4-s3-encode-eta3-is-1-p)
       (pi4-s3-encode-2eta3-is-0-p)
       (pi4-s3-encode-computes-p)
       (= (pi4-s3-suspension-kernel-generator) 2)))

(defun pi4-s3-cubical-encode-residual-p ()
  "HONEST.  We now have an encode MAP at pi_4 (not just pi_1): its values reduce
(Hopf invariant mod 2, eta_3 |-> 1, 2.eta_3 |-> 0).  What is NOT done: the FULL
cubical normalisation -- || Omega^4 S^3 ||_0 reducing AS A TYPE to Z/2 -- which
needs the higher-loop representability (the inc12-14 / inc20 wall); and the
encode's iso-property rests on encoded EHP exactness.  So the encode values
compute (T), AND the cubical table stays :stalled (pi-n (:sphere 3) 4)."
  (and (pi4-s3-encode-computes-p)
       (eq (pi-n (list :sphere 3) 4) :stalled)))
