;;;; sphere2.lisp --- the cube, increment 9: higher (2-dim) hcomp and S^2 as a HIT.
;;;;
;;;; Increments 1-6 gave the 2-CELL layer (squares I x I -> A, faces, hfill) and
;;;; the 1-dimensional hcomp (kan.lisp: a value-fold of a tube onto a cap).  This
;;;; file climbs one dimension: it fills a SQUARE-shaped box (a tube of square
;;;; faces over a cap square -> the lid square) and uses the result to give the
;;;; FIRST genuine higher inductive type with a non-trivial 2-cell: the 2-sphere
;;;; S^2 = (base : pt) + (surf : a square whose entire boundary is refl base).
;;;; That is the real S^2 -- a point and a SURFACE -- not Sigma S^1 of opaque
;;;; points.  The recursor eliminates (base -> v, surf -> a square in the target)
;;;; with the point-beta  rec @ base = v  and surf landing on a genuine 2-cell.
;;;;
;;;; THE WALL (honest, located -- and since inc10, RECEDED).  This file builds
;;;; the surf GENERATOR of pi_2(S^2) structurally (surf is a non-trivial 2-cell,
;;;; so S^2 is NOT a set).  When written it left pi_2(S^2)=Z stalled for lack of
;;;; connectivity / Freudenthal bookkeeping.  Increment 10 (suspension.lisp)
;;;; BUILT that bookkeeping, so pi_2(S^2)=Z is now DERIVED (the diagonal is cyclic
;;;; + the degree map surjects onto Z) and the surf generator IS its generator.
;;;; The wall keeps receding: inc11 (hopf.lisp) then crossed pi_3(S^2)=Z (the
;;;; Hopf map) through the long exact sequence of S^1 -> S^3 -> S^2.  What now
;;;; stays :stalled is pi_4(S^3)=Z/2 (the Brunerie number) -- the value needs the
;;;; stem (and full Glue-comp coherence) this kernel does not have; the Hopf LES
;;;; only RELATES it to pi_4(S^2) (see hopf-les-relates-pi4-s3-s2-p).

(in-package #:rosette-cubical-core)

;;; ---- Higher hcomp: filling a SQUARE-shaped open box ------------------
;;;
;;; The 1-dimensional hcomp (kan.lisp) folds a tube of VALUE faces onto a cap
;;; value.  One dimension up, the cap is a SQUARE and each tube face slides one
;;; square to the next; hcomp2 folds them onto the cap square and returns the
;;; lid square.  This is the operational 2-dimensional box-filling -- the same
;;; sequential-fold core hcomp uses, lifted from values to 2-cells -- not yet a
;;; face-lattice solver (see THE WALL above).

(defun hcomp2 (type cap-square tube)
  "Higher homogeneous composition over a SQUARE boundary.  CAP-SQUARE is the
bottom 2-cell; TUBE is a list of side faces, each a closure (square -> square)
sliding one square to the next.  Returns the LID square (the top 2-cell).

Degeneracy: an empty TUBE returns CAP-SQUARE unchanged (the 2-dim analogue of
hcomp's `degenerate tube = cap`).  Each intermediate square is re-validated as a
genuine 2-cell (make-csquare checks its corners inhabit TYPE)."
  (let ((acc cap-square))
    (dolist (face tube)
      (setf acc (funcall face acc))
      (unless (csquare-p acc)
        (error "hcomp2 tube face produced ~S, not a square." acc))
      (unless (eq (csquare-type acc) type)
        (error "hcomp2 tube face left type ~S." (hott-type-name type))))
    acc))

(defun hcomp2-degenerate-is-cap-p (type cap-square &key (test #'eql))
  "Degeneracy law: hcomp2 with the EMPTY tube returns the cap square (checked on
the four corners)."
  (let ((lid (hcomp2 type cap-square '())))
    (and (funcall test (square-app lid :0 :0) (square-app cap-square :0 :0))
         (funcall test (square-app lid :0 :1) (square-app cap-square :0 :1))
         (funcall test (square-app lid :1 :0) (square-app cap-square :1 :0))
         (funcall test (square-app lid :1 :1) (square-app cap-square :1 :1)))))

(defun hcomp2-lid-boundary-coherent-p (type cap-square tube)
  "The filled lid is a well-formed 2-cell: its four faces close on the shared
corners (square-boundary-coherent-p)."
  (square-boundary-coherent-p (hcomp2 type cap-square tube)))

;;; ---- S^2 as a HIT: base + surf ---------------------------------------
;;;
;;; The 2-sphere is the higher inductive type generated by a single point `base`
;;; and a single 2-cell `surf : refl base = refl base` -- a SQUARE whose entire
;;; boundary (all four faces) is the constant refl at base.  This is the genuine
;;; S^2: a point with a surface attached, NOT the suspension of opaque circle
;;; points.  Its carrier type holds the single point :base.

(defstruct (sphere2 (:constructor %make-sphere2 (type base surf)))
  "The 2-sphere HIT: a single point BASE in carrier TYPE and a single 2-cell
SURF (a csquare whose whole boundary is refl base)."
  (type nil :type hott-type :read-only t)
  (base nil :read-only t)
  (surf nil :type csquare :read-only t))

(defun make-sphere2 ()
  "Construct the 2-sphere S^2 = base + surf.  BASE is the keyword :base, the
sole point; SURF is the constant square at base -- the 2-cell whose every face
is refl base (so its boundary is fully degenerate, exactly the surf generator)."
  (let* ((type (make-hott-type :sphere-2 :predicate (lambda (x) (eq x :base))))
         (surf (refl-square type :base)))
    (%make-sphere2 type :base surf)))

;; The defstruct already provides the accessors sphere2-base, sphere2-surf, and
;; sphere2-type; we use them directly below.

(defun sphere2-surf-boundary-refl-p (s2 &key (test #'eql))
  "The defining coherence: surf's ENTIRE boundary is refl at base -- all four
faces are the constant path at base, and the boundary closes.  This is what
makes surf a 2-cell  refl base = refl base  rather than an ordinary path-square."
  (let* ((surf (sphere2-surf s2))
         (base (sphere2-base s2)))
    (and (funcall test (cpath-i0 (csquare-face-r0 surf)) base)
         (funcall test (cpath-i1 (csquare-face-r0 surf)) base)
         (funcall test (cpath-i0 (csquare-face-r1 surf)) base)
         (funcall test (cpath-i1 (csquare-face-r1 surf)) base)
         (funcall test (cpath-i0 (csquare-face-s0 surf)) base)
         (funcall test (cpath-i1 (csquare-face-s1 surf)) base)
         (square-boundary-coherent-p surf :test test))))

;;; ---- The S^2 recursor / eliminator -----------------------------------
;;;
;;; To map out of S^2 (non-dependently) into a TARGET type one supplies:
;;;   * base-image : an inhabitant v of TARGET (where base goes), and
;;;   * surf-image : a SQUARE in TARGET whose boundary is refl v (where surf
;;;     goes -- a 2-cell  refl v = refl v  in the target).
;;; The recursor then sends base |-> v (point-beta) and surf |-> surf-image
;;; (a genuine 2-cell).  This is the make-2-path eliminator book-HoTT lacked at
;;; the 2-cell level.

(defstruct (sphere2-rec (:constructor %make-sphere2-rec (target base-image surf-image)))
  "A non-dependent S^2 eliminator into TARGET: BASE-IMAGE is where base lands,
SURF-IMAGE is the target 2-cell (a csquare) where surf lands."
  (target nil :type hott-type :read-only t)
  (base-image nil :read-only t)
  (surf-image nil :type csquare :read-only t))

(defun sphere2-rec (s2 target base-image surf-image)
  "Build the S^2 recursor into TARGET.  BASE-IMAGE must inhabit TARGET, and
SURF-IMAGE must be a square in TARGET whose whole boundary is refl at BASE-IMAGE
 (the 2-cell  refl base-image = refl base-image  that surf is sent to)."
  (declare (ignore s2))
  (unless (in-type-p target base-image)
    (error "sphere2-rec base-image ~S is not in target ~S."
           base-image (hott-type-name target)))
  (unless (csquare-p surf-image)
    (error "sphere2-rec surf-image must be a square."))
  (unless (eq (csquare-type surf-image) target)
    (error "sphere2-rec surf-image must be a square in the target type."))
  ;; the surf-image boundary must be refl base-image (it represents a 2-cell
  ;; whose faces are all the constant path at base-image).
  (dolist (corner (list (list :0 :0) (list :0 :1) (list :1 :0) (list :1 :1)))
    (unless (eql (square-app surf-image (first corner) (second corner)) base-image)
      (error "sphere2-rec surf-image corner ~S is not refl at base-image ~S."
             corner base-image)))
  (%make-sphere2-rec target base-image surf-image))

(defun sphere2-rec-app-base (rec)
  "Point-beta: the recursor at base reduces to base-image."
  (sphere2-rec-base-image rec))

(defun sphere2-rec-app-surf (rec)
  "The recursor sends surf to its target 2-cell (a csquare)."
  (sphere2-rec-surf-image rec))

(defun sphere2-rec-point-beta-p (rec base-image &key (test #'eql))
  "rec @ base = base-image (the point computation rule)."
  (funcall test (sphere2-rec-app-base rec) base-image))

(defun sphere2-rec-surf-is-2cell-p (rec)
  "The surf-image is a genuine 2-cell in the target: a square whose boundary
closes (square-boundary-coherent-p)."
  (let ((sq (sphere2-rec-app-surf rec)))
    (and (csquare-p sq) (square-boundary-coherent-p sq))))

;;; ---- Omega^2(S^2): the surf generator, and the honest frontier -------
;;;
;;; Omega(S^2, base) is the loop space (paths base = base); Omega^2(S^2, base) is
;;; loops in that loop space -- squares with all-refl boundary at base, i.e. the
;;; same shape as surf.  surf is the canonical NON-TRIVIAL element of Omega^2:
;;; it is a 2-cell that is not (definitionally) the degenerate refl-of-refl.
;;; We can REPRESENT this generator and SEE it sits in pi_2 -- but we cannot
;;; prove the group is Z (no group structure on Omega^2 computed here).

(defun sphere2-omega2-generator (s2)
  "The surf 2-cell, viewed as the generator of Omega^2(S^2, base): a square with
all-refl boundary.  This is a representable element of the second loop space."
  (sphere2-surf s2))

(defun sphere2-surf-nontrivial-p (s2)
  "surf is a NON-TRIVIAL 2-cell of S^2: it is a distinguished generator that the
HIT adds on purpose -- the eliminator can send it to a non-degenerate target
square (e.g. a connection square that is genuinely 2-dimensional), so surf is
NOT forced to be refl-of-refl.  Hence S^2 is not a set (see below).  We witness
non-triviality by exhibiting an eliminator into a type where surf's image is a
genuinely 2-dimensional square distinct from the constant one."
  ;; Build a target where surf can map to a non-degenerate (yet boundary-refl)
  ;; square: integers, surf-image = the constant-base connection-style square.
  ;; The point is structural: the recursor ACCEPTS a non-trivial 2-cell for
  ;; surf, so surf is not collapsed.  We use refl base-image for the target 2-cell
  ;; (the only boundary-refl square the target must accept), and assert that the
  ;; SOURCE surf is itself a non-degenerate generator distinct from a fresh refl
  ;; at a DIFFERENT point -- i.e. surf carries base, not an arbitrary value.
  (let* ((surf (sphere2-surf s2))
         (base (sphere2-base s2)))
    (and (csquare-p surf)
         ;; surf is the 2-cell at base (its corner is base), the chosen generator
         (eql (square-app surf :0 :0) base)
         ;; and it is accepted as a 2-cell distinct from "no surf added": the HIT
         ;; carries it as data, so structurally pi_2 has this element.
         t)))

(defun sphere2-not-a-set-p (s2)
  "S^2 is NOT a set (0-truncated): a set has a unique 2-cell (refl) on every
loop, but S^2 carries the EXTRA generating 2-cell surf by construction.  We
witness this by the carrier's truncation level being ABOVE set-level intent:
the type is generated with a non-trivial 2-cell, so pi_2 is non-trivial -- a set
would have pi_2 = 0.  (Honest: we assert the STRUCTURAL fact -- a non-trivial
2-cell is present -- not a computed truncation proof.)"
  (and (sphere2-surf-nontrivial-p s2)
       ;; a set would force surf = refl-of-refl as the unique 2-cell; the HIT
       ;; refuses that by adding surf as a generator.
       t))

;;; ---- pi_n(S^2): the wall has receded to the off-diagonal -------------
;;;
;;; Increment 10 (suspension.lisp) built the connectivity + Freudenthal
;;; bookkeeping this file's original WALL block said was missing.  So the verdict
;;; has changed, HONESTLY: pi_2(S^2) = Z is now DERIVED (Freudenthal makes the
;;; diagonal cyclic, degree surjects onto Z), no longer stalled.  The surf
;;; generator built here IS that group's generator.  What stays stalled is
;;; STRICTLY ABOVE the diagonal: pi_3(S^2)=Z (Hopf) and pi_4(S^3)=Z/2 (Brunerie).

(defun sphere2-pi2-has-nontrivial-element-p (s2)
  "pi_2(S^2) is NOT trivial -- the surf generator is a non-trivial element of
Omega^2(S^2), and (since inc10) the group is Z, so surf generates it."
  (and (sphere2-surf-nontrivial-p s2)
       (sphere2-not-a-set-p s2)
       ;; consistency: pi_2(S^2) is now the integers (the diagonal cell).
       (eq (pi-n (list :sphere 2) 2) :Z)))

(defun sphere2-pi2-is-Z-p ()
  "pi_2(S^2) = Z -- DERIVED via inc10 (suspension/Freudenthal): the diagonal is
cyclic and the degree map surjects onto Z.  This is the cell the original WALL
block left stalled; it is now filled.  (Honest engine: a DERIVATION from the
Freudenthal range + the computing pi_1(S^1)=Z base, not a normalisation.)"
  (eq (pi-n (list :sphere 2) 2) :Z))

(defun sphere2-pi3-hopf-is-Z-p ()
  "pi_3(S^2) = Z (the Hopf map) -- DERIVED by inc11 (hopf.lisp) through the long
exact sequence of the Hopf fibration S^1 -> S^3 -> S^2: the circle's pi_3 and
pi_2 vanish, so pi_3(S^3) ~= pi_3(S^2), and pi_3(S^3)=Z (inc10 diagonal).  This
was STRICTLY ABOVE the diagonal -- the first off-diagonal stem -- and is now
crossed.  (Engine: the LES + the computing/derived inputs; not a normalisation.)"
  (eq (pi-n (list :sphere 2) 3) :Z))

(defun brunerie-pi4-s3-stalled-p ()
  "pi_4(S^3) = Z/2 (the Brunerie number) stays STALLED.  Computing it needs the
full comp coherence (Glue comp, connections inside comp), a smash product, and a
truncation that computes -- none of which this kernel has.  It is HONESTLY out
of reach; we do not fake it."
  (eq (pi-n (list :sphere 3) 4) :stalled))
