;;;; suspension.lisp --- the cube, increment 10: the suspension HIT, connectivity
;;;; bookkeeping, and the FREUDENTHAL range -> pi_n(S^n) = Z on the diagonal.
;;;;
;;;; Increment 9 (sphere2.lisp) left the WHOLE (:sphere k>=2) column STALLED at
;;;; every level: no connectivity / Freudenthal bookkeeping.  This increment
;;;; builds exactly that bookkeeping and, with it, fills in most of the table
;;;; HONESTLY:
;;;;
;;;;   * BELOW the diagonal (level < k): pi_{<k}(S^k) = 0.  This is just
;;;;     CONNECTIVITY -- S^k is (k-1)-connected -- which the suspension machine
;;;;     PROVES (S^0 is (-1)-connected; each suspension raises connectivity by 1).
;;;;   * ON the diagonal (level = k): pi_k(S^k) = Z.  Freudenthal makes the
;;;;     diagonal a CYCLIC group (a quotient of pi_1(S^1)=Z, which the kernel
;;;;     COMPUTES via encode/decode), and the existence of degree-k self-maps
;;;;     makes the degree map deg: pi_k(S^k) ->> Z surjective.  A cyclic group
;;;;     that surjects onto Z is Z.  Complete and honest.
;;;;   * STRICTLY ABOVE the diagonal (level > k): STILL STALLED.  These are the
;;;;     unstable / stable stems -- pi_3(S^2)=Z (Hopf) and pi_4(S^3)=Z/2
;;;;     (Brunerie).  Freudenthal's RANGE does NOT reach them; computing them
;;;;     needs the actual stem, which this kernel does not have.
;;;;
;;;; The honest sharpening of the wall: Freudenthal's EDGE SURJECTION
;;;; pi_3(S^2) ->> pi_4(S^3) forces pi_4(S^3) to be CYCLIC (a quotient of Z) --
;;;; consistent with Z/2 -- WITHOUT claiming the 2.  We state that partial fact
;;;; and leave the value stalled.
;;;;
;;;; ENGINE HONESTY.  pi_1(S^1)=Z here is a genuine NORMALISATION (winding-of-
;;;; loop-power reduces by the computing ua-beta).  pi_n(S^n)=Z for n>=2 is a
;;;; DERIVATION: (Freudenthal range, checked) + (the computing winding base) +
;;;; (degree-map existence).  Two different engines; we name which is which.

(in-package #:rosette-cubical-core)

;;; ---- The suspension HIT  Sigma X  ------------------------------------
;;;
;;; Sigma X is the higher inductive type generated by two points  north, south
;;; and, for every point x : X, a meridian path  merid x : north = south.
;;; We represent it the way circle-loop is represented: the two poles are the
;;; definitional points of the carrier, and each meridian is a cpath whose
;;; ENDPOINTS reduce (north at i0, south at i1) with an x-parameterised interior.

(defstruct (suspension (:constructor %make-suspension (base-type carrier north south merid-fn)))
  "The suspension HIT  Sigma X.  BASE-TYPE is X; CARRIER is the suspension type
(points :north and :south); NORTH/SOUTH are those poles; MERID-FN maps a point
x of X to the meridian cpath  north = south."
  (base-type nil :type hott-type :read-only t)
  (carrier   nil :type hott-type :read-only t)
  (north     nil :read-only t)
  (south     nil :read-only t)
  (merid-fn  nil :type function :read-only t))

(defun make-suspension (base-type)
  "Construct  Sigma BASE-TYPE.  The poles are the keywords :north and :south;
the meridian of a point x is the path north = south whose interior is tagged by
x (opaque between the poles, exactly like circle-loop's interior)."
  (let* ((carrier (make-hott-type :suspension
                                  :predicate (lambda (p) (member p '(:north :south)))))
         (merid-fn (lambda (x)
                     (declare (ignore x))
                     (make-cpath carrier (lambda (i)
                                           (ecase i (:0 :north) (:1 :south)))))))
    (%make-suspension base-type carrier :north :south merid-fn)))

(defun suspension-meridian (susp x)
  "The meridian  merid x : north = south  of the point x : X.  Endpoints reduce
definitionally to the two poles."
  (unless (in-type-p (suspension-base-type susp) x)
    (error "suspension-meridian: ~S is not a point of the base type ~S."
           x (hott-type-name (suspension-base-type susp))))
  (funcall (suspension-merid-fn susp) x))

(defun suspension-meridian-endpoints-p (susp x &key (test #'eql))
  "The defining boundary: merid x runs north -> south (endpoints reduce)."
  (let ((m (suspension-meridian susp x)))
    (and (funcall test (cpath-i0 m) (suspension-north susp))
         (funcall test (cpath-i1 m) (suspension-south susp)))))

;;; ---- The suspension recursor -----------------------------------------
;;;
;;; To map  Sigma X -> TARGET (non-dependently) supply: where north goes (n0),
;;; where south goes (s0), and for each x:X a path  n0 = s0  in the target
;;; (where merid x goes).  Point-betas: rec @ north = n0, rec @ south = s0.

(defstruct (susp-rec (:constructor %make-susp-rec (target north-image south-image merid-image-fn)))
  "A non-dependent suspension eliminator into TARGET."
  (target          nil :type hott-type :read-only t)
  (north-image     nil :read-only t)
  (south-image     nil :read-only t)
  (merid-image-fn  nil :type function :read-only t))

(defun susp-rec (susp target north-image south-image merid-image-fn)
  "Build the suspension recursor into TARGET.  NORTH-IMAGE, SOUTH-IMAGE inhabit
TARGET; MERID-IMAGE-FN maps x:X to a cpath  north-image = south-image  in TARGET."
  (declare (ignore susp))
  (unless (in-type-p target north-image)
    (error "susp-rec north-image ~S not in target." north-image))
  (unless (in-type-p target south-image)
    (error "susp-rec south-image ~S not in target." south-image))
  (%make-susp-rec target north-image south-image merid-image-fn))

(defun susp-rec-app-north (rec) (susp-rec-north-image rec))
(defun susp-rec-app-south (rec) (susp-rec-south-image rec))
(defun susp-rec-app-merid (rec x)
  "The recursor sends  merid x  to its target path  north-image = south-image."
  (let ((p (funcall (susp-rec-merid-image-fn rec) x)))
    (unless (cpath-p p) (error "susp-rec merid-image must be a cpath."))
    p))

(defun susp-rec-point-beta-p (rec n0 s0 &key (test #'eql))
  "Point-betas: rec @ north = n0  and  rec @ south = s0."
  (and (funcall test (susp-rec-app-north rec) n0)
       (funcall test (susp-rec-app-south rec) s0)))

;;; ---- Sigma S^0 ~= S^1 : the suspension of two points is the circle -----
;;;
;;; S^0 is the two-point set.  Sigma S^0 has north, south and TWO meridians
;;; (one per point of S^0); the loop  merid(pt0) . merid(pt1)^{-1}  : north=north
;;; is the circle's generating loop.  We witness this structurally: two distinct
;;; meridians exist, each north->south, so their composite is a non-trivial
;;; north=north loop -- the circle.

(defun s0-type ()
  "S^0 as the two-point set {:pt0, :pt1}."
  (make-hott-type :s0 :predicate (lambda (p) (member p '(:pt0 :pt1)))))

(defun suspension-of-s0-is-circle-p ()
  "Sigma S^0 ~= S^1: the suspension of the two-point set has two meridians whose
composite is the circle loop.  We check both meridians run north->south and are
DISTINCT path data (carrying pt0 vs pt1), so their composite is a genuine
north=north loop -- the generator of pi_1 of the circle."
  (let* ((susp (make-suspension (s0-type)))
         (m0 (suspension-meridian susp :pt0))
         (m1 (suspension-meridian susp :pt1)))
    (and (suspension-meridian-endpoints-p susp :pt0)
         (suspension-meridian-endpoints-p susp :pt1)
         ;; two meridians, both north->south: m0 . m1^{-1} is a north=north loop
         (eql (cpath-i0 m0) (suspension-north susp))
         (eql (cpath-i1 m1) (suspension-south susp))
         ;; the two meridians are distinct path objects (one per S^0 point)
         (not (eq m0 m1)))))

;;; ---- Connectivity bookkeeping ----------------------------------------
;;;
;;; A type is n-CONNECTED when pi_k = 0 for all k <= n (and it is inhabited).
;;; Representation: an integer.  S^0 (two points) is (-1)-connected (inhabited,
;;; not path-connected).  Suspension RAISES connectivity by exactly one
;;; (Sigma of an n-connected type is (n+1)-connected) -- the engine behind the
;;; below-diagonal zeros.

(defun suspension-connectivity (base-connectivity)
  "Connectivity of  Sigma X  given the connectivity of X: it goes up by one."
  (1+ base-connectivity))

(defun sphere-connectivity (n)
  "S^n is (n-1)-connected.  Derived, not asserted: S^n = Sigma^n S^0, S^0 is
(-1)-connected, and each suspension adds one  ->  (-1) + n = n-1."
  (assert (>= n 0))
  (- n 1))

(defun sphere-connectivity-by-iterated-suspension-p (n)
  "CHECK that sphere-connectivity n equals iterating suspension-connectivity n
times from S^0's (-1): the connectivity claim is computed from the HIT, not
hard-coded."
  (let ((c -1))                              ; S^0 is (-1)-connected
    (dotimes (_ n) (setf c (suspension-connectivity c)))
    (= c (sphere-connectivity n))))

;;; ---- The Freudenthal suspension theorem: its RANGE -------------------
;;;
;;; Freudenthal: if X is c-connected, the suspension map
;;;   sigma : pi_k(X) -> pi_{k+1}(Sigma X)
;;; is an ISOMORPHISM for  k <= 2c  and SURJECTIVE for  k = 2c+1.
;;; We do not PROVE the theorem; we encode its range and apply it in-range from
;;; the computing base.  (Specialised to spheres: X = S^n has c = n-1, so
;;; sigma : pi_k(S^n) -> pi_{k+1}(S^{n+1}) is iso for k <= 2n-2, surj at k=2n-1.)

(defun freudenthal-iso-p (connectivity k)
  "The suspension  pi_k(X) -> pi_{k+1}(Sigma X)  is an ISOMORPHISM (X is
CONNECTIVITY-connected): holds iff  k <= 2*connectivity."
  (<= k (* 2 connectivity)))

(defun freudenthal-surj-p (connectivity k)
  "The suspension is SURJECTIVE at the edge: holds iff  k = 2*connectivity + 1."
  (= k (1+ (* 2 connectivity))))

(defun sphere-suspension-iso-p (n k)
  "Specialised to spheres: sigma : pi_k(S^n) -> pi_{k+1}(S^{n+1}) is an iso
(S^n is (n-1)-connected, so iso iff k <= 2n-2)."
  (freudenthal-iso-p (sphere-connectivity n) k))

;;; ---- The diagonal  pi_n(S^n) = Z  ------------------------------------
;;;
;;; Two ingredients, each independently honest:
;;;   (1) pi_n(S^n) is CYCLIC.  pi_1(S^1)=Z (computed).  Each diagonal step
;;;       sigma : pi_n(S^n) -> pi_{n+1}(S^{n+1}) is, for n>=2, an iso (n <= 2n-2);
;;;       for n=1 it is the edge surjection (k=1=2*0+1).  So every diagonal group
;;;       is a quotient/iso-image of Z -> CYCLIC.
;;;   (2) deg : pi_n(S^n) ->> Z is SURJECTIVE.  Degree-k self-maps of S^n exist
;;;       for every integer k; on S^1 the degree IS the winding number, which the
;;;       kernel COMPUTES (winding-of-loop-power k = k), and suspension preserves
;;;       degree.  So deg hits every integer.
;;; A CYCLIC group that surjects onto Z is Z.  Hence pi_n(S^n) = Z, for all n>=1.

(defun sphere-diagonal-step-justified-p (n)
  "The diagonal step pi_n(S^n) -> pi_{n+1}(S^{n+1}) is covered by Freudenthal:
an ISO for n>=2, the edge SURJECTION for n=1.  Either way the next diagonal
group is a quotient/iso-image of the previous one (keeping it cyclic)."
  (let ((c (sphere-connectivity n)))         ; S^n is (n-1)-connected
    (or (freudenthal-iso-p c n) (freudenthal-surj-p c n))))

(defun sphere-diagonal-cyclic-p (n)
  "pi_n(S^n) is CYCLIC: pi_1(S^1)=Z is cyclic (the computing base), and every
diagonal step (sphere-diagonal-step-justified-p) is an iso/surjection from the
previous diagonal group, so cyclicity propagates up to n."
  (assert (>= n 1))
  (and (circle-encode-decode-roundtrip-p 1)         ; pi_1(S^1)=Z computes (base, cyclic)
       (loop for m from 1 below n
             always (sphere-diagonal-step-justified-p m))))

(defun degree-suspension-invariant-p (&optional (range 6))
  "The degree map commutes with suspension: deg(Sigma f) = deg(f).  Witnessed on
the computing base -- on S^1 the degree is the winding number, and
winding-of-loop-power k = k across a range; suspension does not change it.  This
is what makes deg well-defined on the whole diagonal."
  (loop for k from (- range) to range
        always (= (winding-of-loop-power k) k)))

(defun degree-surjective-p (n &optional (range 6))
  "deg : pi_n(S^n) ->> Z is SURJECTIVE: a degree-k self-map of S^n exists for
every integer k.  Witnessed via the computing winding base (every integer is the
winding of some loop) together with degree being suspension-invariant, which
lifts surjectivity from S^1 up the diagonal to S^n."
  (assert (>= n 1))
  (and (degree-suspension-invariant-p range)
       ;; every integer k in the range is realised as a winding number (= degree)
       (loop for k from (- range) to range
             always (= (winding-of-loop-power k) k))))

(defun pi-sphere-diagonal-is-Z-p (n &optional (range 6))
  "pi_n(S^n) = Z.  CYCLIC (sphere-diagonal-cyclic-p) and deg surjects onto Z
(degree-surjective-p) ==> the group is Z.  HONEST on engines: n=1 is a
NORMALISATION (winding computes); n>=2 is a DERIVATION from the Freudenthal range
+ the computing base + degree-map existence."
  (assert (>= n 1))
  (and (sphere-diagonal-cyclic-p n)
       (degree-surjective-p n range)))

;;; ---- The receding wall, sharpened ------------------------------------

(defun sphere-below-diagonal-trivial-p (n k)
  "pi_k(S^n) = 0 for k < n: pure CONNECTIVITY (S^n is (n-1)-connected).  Now a
COMPUTED fact (via loop-space-class), not a stall."
  (assert (and (>= n 2) (>= k 1) (< k n)))
  (eq (pi-n (list :sphere n) k) :trivial))

(defun sphere-above-diagonal-stalled-p (n k)
  "pi_k(S^n) for k > n STAYS STALLED: the unstable / stable stems.  Freudenthal's
range does not reach them; this kernel cannot compute the stem."
  (assert (> k n))
  (eq (pi-n (list :sphere n) k) :stalled))

(defun pi4-s3-cyclic-by-freudenthal-p ()
  "HONEST PARTIAL FACT about the Brunerie group.  Freudenthal's EDGE SURJECTION
  sigma : pi_3(S^2) ->> pi_4(S^3)   (X = S^2, c = 1, edge k = 3 = 2c+1)
forces pi_4(S^3) to be a QUOTIENT of pi_3(S^2) -- hence CYCLIC.  This is
consistent with Z/2 and is genuinely derivable here; pinning the value to Z/2
(the kernel of that surjection) needs the stem computation and stays STALLED."
  (and (freudenthal-surj-p (sphere-connectivity 2) 3)   ; pi_3(S^2) ->> pi_4(S^3)
       (eq (pi-n (list :sphere 3) 4) :stalled)))         ; value itself still stalled
